# Refinitiv Data Library for Python
## Content - Historical Pricing - Synchronous calls

This notebook demonstrates how to retrieve Historical Pricing data from the Refinitiv Data Platform OR via Eikon or Refinitiv Workspace.   

Whilst this notebook uses synchronous calls, there is an async technique which will be explored in a future example/tutorial.

## Import the library and load credentials

Credentials used by this and the other tutorials notebooks are stored in the **Configuration/credentials.ipynb** file.     

You should have edited the **Configuration/credentials.ipynb** to set your credentials as part of the **Quick Start** step.

In [1]:
from refinitiv.data.content import historical_pricing
import datetime
import json

%run ../../Configuration/credentials.ipynb

## Open the session of your choice

Use our helper function in the Credentials notebook, **open_session(session_type)**, to create and open a session to connect to the 
- Refinitiv Data Platform directly (session_type="rdp") or via 
- Eikon 4 or Refinitiv Workspace (session_type="desktop")   

You can also set a default in the **credentials** notebook

**Note**: You cannot currently request Historical Pricing data from a Deployed session

In [2]:
open_session('rdp')

## Request Historical Pricing data

### Historical Price Events

NOTE: We have not specified any start or end times, so the request defaults to the 20 most recent events

In [3]:
response = historical_pricing.events.Definition("VOD.L").get_data()
# Extract in DataFrame format
response.data.df

,EVENT_TYPE,RTL,SEQNUM,TRDXID_1,TRDPRC_1,TRDVOL_1,VWAP,BID,BIDSIZE,ASK,...,TRNOVR_UNS,NETCHNG_1,MMT_CLASS,TR_TRD_FLG,ACVOL_UNS,OPEN_PRC,HIGH_1,LOW_1,MID_PRICE,QUALIFIERS
2021-08-04 10:32:56.904,quote,20608,1628642,<NA>,<NA>,<NA>,<NA>,117.56,6621,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.58,[BID_TONE]
2021-08-04 10:32:56.904,quote,20624,1628643,<NA>,<NA>,<NA>,<NA>,117.56,9621,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.58,[BID_TONE]
2021-08-04 10:32:56.907,quote,20640,1628644,<NA>,<NA>,<NA>,<NA>,117.56,6209,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.58,[BID_TONE]
2021-08-04 10:32:56.907,quote,20656,1628645,<NA>,<NA>,<NA>,<NA>,117.56,6209,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.58,[ASK_TONE]
2021-08-04 10:32:56.910,quote,20672,1628646,<NA>,<NA>,<NA>,<NA>,117.58,210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.59,[BID_TONE]
2021-08-04 10:32:56.928,quote,20688,1628647,<NA>,<NA>,<NA>,<NA>,117.58,210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.59,[ASK_TONE]
2021-08-04 10:32:56.941,quote,20704,1628648,<NA>,<NA>,<NA>,<NA>,117.58,210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.59,[ASK_TONE]
2021-08-04 10:32:57.003,quote,20720,1628651,<NA>,<NA>,<NA>,<NA>,117.58,210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.59,[ASK_TONE]
2021-08-04 10:33:04.389,quote,20736,1628905,<NA>,<NA>,<NA>,<NA>,117.58,210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.59,[ASK_TONE]
2021-08-04 10:33:11.044,quote,20752,1629396,<NA>,<NA>,<NA>,<NA>,117.58,210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.59,[ASK_TONE]
2021-08-04 10:33:20.652,trade,20782,137048,XLON,117.58,210,117.97432,117.58,210,117.6,...,903698975.073,-0.12,12-------PH---,OB,7660134,117.88,118.36,117.52,<NA>,A[ACT_FLAG1];A[CONDCODE_1];[CONDCODE_2];Y [EL...
2021-08-04 10:33:20.653,quote,20816,1630131,<NA>,<NA>,<NA>,<NA>,117.56,3209,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.58,[BID_TONE]
2021-08-04 10:33:20.653,quote,20832,1630132,<NA>,<NA>,<NA>,<NA>,117.54,35777,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.57,[BID_TONE]
2021-08-04 10:33:20.653,quote,20848,1630133,<NA>,<NA>,<NA>,<NA>,117.54,35777,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.57,[ASK_TONE]
2021-08-04 10:33:20.653,quote,20800,1630130,<NA>,<NA>,<NA>,<NA>,117.56,6621,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.58,[BID_TONE]
2021-08-04 10:33:20.654,quote,20864,1630134,<NA>,<NA>,<NA>,<NA>,117.54,30210,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.57,[BID_TONE]
2021-08-04 10:33:20.654,quote,20880,1630135,<NA>,<NA>,<NA>,<NA>,117.54,20477,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.57,[BID_TONE]
2021-08-04 10:33:20.664,quote,20896,1630138,<NA>,<NA>,<NA>,<NA>,117.54,20477,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.57,[ASK_TONE]
2021-08-04 10:33:21.175,quote,20912,1630220,<NA>,<NA>,<NA>,<NA>,117.54,20477,117.6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117.57,[ASK_TONE]
2021-08-04 10:33:22.077,trade,20942,160273,XLON,117.5877,4,117.97431,117.54,20477,117.6,...,903724137.224,<NA>,45------MP----,RX,7660348,117.88,118.36,117.52,<NA>,R[ACT_FLAG1];R[CONDCODE_1];[CONDCODE_2];N [EL...

#### Data is also available in the Raw JSON format

In [4]:
# JSON format (display only 200 characters of headers + data to minimise output)
if (response.is_success):
    print(json.dumps(response.data.raw['universe'], indent=2),
          'Headers:',
          json.dumps(response.data.raw['headers'], indent=2)[0:200],
          'Data:',
          json.dumps(response.data.raw['data'], indent=2)[0:200])
else:
    print(response.http_status)

{
  "ric": "VOD.L"
} Headers: [
  {
    "name": "DATE_TIME",
    "type": "string"
  },
  {
    "name": "EVENT_TYPE",
    "type": "string"
  },
  {
    "name": "RTL",
    "type": "number",
    "decimalChar": "."
  },
  {
    "name" Data: [
  [
    "trade",
    20942,
    "160273",
    "XLON",
    117.5877,
    4,
    117.97431,
    117.54,
    20477,
    117.6,
    13775,
    "\u21e7",
    null,
    null,
    null,
    "10100913584143

#### Historical Price events with some optional parameters
Specify start + end time and Corrections parameters

In [3]:
response = historical_pricing.events.Definition(
    universe = "AAPL.O", 
    start = datetime.timedelta(-1), 
    end = datetime.timedelta(0),
    adjustments = [
        historical_pricing.Adjustments.EXCHANGE_CORRECTION,
        historical_pricing.Adjustments.MANUAL_CORRECTION
    ]).get_data()
# Extract in DataFrame format
response.data.df

,EVENT_TYPE,RTL,SEQNUM,TRDXID_1,TRDPRC_1,TRDVOL_1,ACVOL_UNS,VWAP,BID,BIDSIZE,...,OPEN_PRC,HIGH_1,LOW_1,IMP_VOLT,BID_MMID1,ASK_MMID1,MID_PRICE,LIMIT_INDQ,SH_SAL_RES,QUALIFIERS
2021-08-03 19:59:53.339,trade,44782,5923601,NAS,147.34,100,59586757,146.7365,147.34,300,...,145.81,148.045,145.18,<NA>,<NA>,<NA>,None,<NA>,<NA>,@ [LSTSALCOND]; [PRC_QL2]
2021-08-03 19:59:53.339,quote,44976,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.34,200,...,<NA>,<NA>,<NA>,<NA>,NAS,NAS,None,BOE,N,[PRC_QL_CD]; [PRC_QL3];A[GV1_TEXT]
2021-08-03 19:59:53.339,quote,44944,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.34,100,...,<NA>,<NA>,<NA>,<NA>,BAT,NAS,None,BOE,N,[PRC_QL_CD]; [PRC_QL3];A[GV1_TEXT]
2021-08-03 19:59:53.339,quote,44912,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.34,100,...,<NA>,<NA>,<NA>,<NA>,NYS,NAS,None,BOE,N,[PRC_QL_CD]; [PRC_QL3];A[GV1_TEXT]
2021-08-03 19:59:53.339,quote,44864,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.34,100,...,<NA>,<NA>,<NA>,<NA>,MMX,NAS,None,BOE,N,[PRC_QL_CD]; [PRC_QL3];A[GV1_TEXT]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-04 10:36:56.511,quote,49152,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.53,300,...,<NA>,<NA>,<NA>,<NA>,NAS,PSE,None,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT]
2021-08-04 10:36:57.120,quote,49168,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.53,300,...,<NA>,<NA>,<NA>,<NA>,NAS,DEX,None,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT]
2021-08-04 10:36:57.120,quote,49184,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.53,300,...,<NA>,<NA>,<NA>,<NA>,NAS,PSE,None,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT]
2021-08-04 10:36:58.091,quote,49200,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.53,300,...,<NA>,<NA>,<NA>,<NA>,NAS,DEX,None,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT]
2021-08-04 10:36:58.091,quote,49216,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147.53,300,...,<NA>,<NA>,<NA>,<NA>,NAS,PSE,None,,N,[PRC_QL_CD]; [PRC_QL3]; [GV1_TEXT]

ERROR!!! Failed to request a new token......
         Token requested error b'{"error":"invalid_grant"   } '
ERROR!!! request a new refresh token has been failed.
The server-mode is disabled, so we do not re-authorize with username/password.
ERROR!!! authentication handler raise an exception.
ValueError('ERROR!!! request a new refresh token has been failed.\nThe server-mode is disabled, so we do not re-authorize with username/password.')

### Historical Price Intraday Summaries  

NOTE: Once again, we have not specified any start or end times, so the request defaults to the 20 most recent price points at the specified interval.

In [11]:
response = historical_pricing.summaries.Definition(
    "VOD.L", 
    count=2,
    interval=historical_pricing.Intervals.FIVE_MINUTES).get_data()
# Extract in DataFrame format
response.data.df

,HIGH_1,LOW_1,OPEN_PRC,TRDPRC_1,NUM_MOVES,ACVOL_UNS,HIGH_YLD,LOW_YLD,OPEN_YLD,YIELD,...,BID_NUMMOV,ASK_HIGH_1,ASK_LOW_1,OPEN_ASK,ASK,ASK_NUMMOV,MID_HIGH,MID_LOW,MID_OPEN,MID_PRICE
2021-08-04 10:25:00,117.78,117.66,117.762,117.66,59,186384,None,None,None,None,...,304,117.8,117.66,117.78,117.68,304,117.78,117.65,117.77,117.66
2021-08-04 10:30:00,117.64,117.5133,117.64,117.5467,122,388112,None,None,None,None,...,649,117.68,117.54,117.68,117.56,649,117.66,117.52,117.66,117.54

#### Historical Price Intraday Summaries with some optional parameters  

Specify a limit of 500 data points and filter for certain MarketSession types

In [12]:
response = historical_pricing.summaries.Definition(
    universe = "IBM.N", 
    interval = historical_pricing.Intervals.ONE_MINUTE,     # Supported intervals: ONE_MINUTE, FIVE_MINUTES, TEN_MINUTES, THIRTY_MINUTES, ONE_HOUR
    count = 500,
    sessions = [
        historical_pricing.MarketSession.PRE, 
        historical_pricing.MarketSession.NORMAL, 
        historical_pricing.MarketSession.POST
    ]).get_data()
# Extract in DataFrame format
response.data.df

,HIGH_1,LOW_1,OPEN_PRC,TRDPRC_1,NUM_MOVES,ACVOL_UNS,HIGH_YLD,LOW_YLD,OPEN_YLD,YIELD,...,BID_NUMMOV,ASK_HIGH_1,ASK_LOW_1,OPEN_ASK,ASK,ASK_NUMMOV,MID_HIGH,MID_LOW,MID_OPEN,MID_PRICE
2021-08-02 18:14:00,141.85,141.85,141.85,141.85,2,101,<NA>,<NA>,<NA>,<NA>,...,484,141.87,141.82,141.83,141.85,484,None,None,None,None
2021-08-02 18:15:00,141.84,141.82,141.84,141.82,5,110,<NA>,<NA>,<NA>,<NA>,...,447,141.87,141.82,141.85,141.85,447,None,None,None,None
2021-08-02 18:16:00,141.88,141.84,141.85,141.88,5,177,<NA>,<NA>,<NA>,<NA>,...,735,141.9,141.84,141.86,141.89,735,None,None,None,None
2021-08-02 18:17:00,141.87,141.87,141.87,141.87,1,101,<NA>,<NA>,<NA>,<NA>,...,251,141.9,141.85,141.89,141.88,251,None,None,None,None
2021-08-02 18:18:00,141.92,141.88,141.88,141.92,6,371,<NA>,<NA>,<NA>,<NA>,...,399,141.93,141.88,141.88,141.93,399,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-03 19:57:00,144.12,144.06,144.11,144.11,62,10177,<NA>,<NA>,<NA>,<NA>,...,733,144.13,144.06,144.12,144.12,733,None,None,None,None
2021-08-03 19:58:00,144.17,144.09,144.12,144.15,99,14340,<NA>,<NA>,<NA>,<NA>,...,827,144.17,144.1,144.12,144.15,827,None,None,None,None
2021-08-03 19:59:00,144.21,143.98,144.15,144.07,286,41901,<NA>,<NA>,<NA>,<NA>,...,1543,144.22,143.99,144.15,144.08,1543,None,None,None,None
2021-08-03 20:00:00,144.07,144.07,144.07,144.07,1,342683,<NA>,<NA>,<NA>,<NA>,...,1,0.0,0.0,0.0,0.0,1,None,None,None,None
2021-08-04 04:44:00,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4.5533,4.5533,4.5533,4.5533,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,None

### Historical Price Interday Summaries

Notice how the **Interval** has not been specified - so the request will use the default 'Daily' interval for the past 20 days

In [13]:
response = historical_pricing.summaries.Definition("IBM.N").get_data()
# Extract in DataFrame format
response.data.df

,TRDPRC_1,HIGH_1,LOW_1,ACVOL_UNS,OPEN_PRC,BID,ASK,TRNOVR_UNS,VWAP,BLKCOUNT,BLKVOLUM,NUM_MOVES,TRD_STATUS,SALTIM
2021-07-07,139.82,140.31,138.93,922100,139.01,139.8,139.82,128772018.455,139.6508,2,473516,5763,1,72600
2021-07-08,140.74,141.31,137.71,1243054,137.78,140.73,140.74,174244317.177,140.1744,2,711594,6194,1,72600
2021-07-09,141.52,141.97,140.85,1085822,141.45,141.49,141.5,153652297.666,141.5078,2,662404,4606,1,72600
2021-07-12,140.92,141.946,140.14,756686,141.43,140.91,140.92,106709325.478,141.0219,2,396883,4910,1,72600
2021-07-13,140.28,140.68,139.64,812849,140.18,140.27,140.28,113956596.611,140.1941,2,416386,6321,1,72600
2021-07-14,139.82,140.75,138.95,1062745,140.72,139.82,139.83,148602798.746,139.8292,2,551786,6257,1,72600
2021-07-15,140.45,140.46,138.82,1024475,139.32,140.44,140.45,143598852.984,140.1682,2,638193,5337,1,72600
2021-07-16,138.9,141.0,138.63,1010654,141.0,138.88,138.9,140826308.459,139.3418,2,507045,6229,1,72600
2021-07-19,137.92,138.49,136.23,1812320,136.55,138.05,138.13,249332695.873,137.5765,2,822535,10033,1,72600
2021-07-20,139.97,144.9,138.7,2071797,143.0,139.97,139.98,293256037.148,141.5467,2,741819,14982,1,72600
2021-07-21,141.3,141.38,139.66,1243445,139.97,141.24,141.3,175418335.127,141.0745,2,798597,5625,1,72600
2021-07-22,140.71,141.75,140.41,946754,141.66,140.71,140.72,133333448.066,140.8322,2,533338,5081,1,72600
2021-07-23,141.34,141.67,140.35,524320,140.96,141.33,141.34,74040629.267,141.2127,2,272251,3908,1,72600
2021-07-26,142.77,142.94,141.24,1491345,141.39,142.76,142.77,212742197.256,142.6512,2,1050245,4637,1,72600
2021-07-27,142.75,143.63,141.6,818186,142.53,142.74,142.75,116740536.535,142.6821,3,339428,5571,1,72600
2021-07-28,141.77,143.01,141.64,740778,143.01,141.75,141.77,105195063.059,142.0062,2,374737,4643,1,72600
2021-07-29,141.93,142.88,141.6,719940,142.33,141.91,141.93,102253402.26,142.0305,2,301664,5126,1,72600
2021-07-30,140.96,141.82,140.79,1480294,141.52,140.96,140.97,208745900.051,141.0165,2,1089259,4652,1,72600
2021-08-02,141.42,143.06,141.03,666697,141.45,141.42,141.43,94423671.397,141.6291,2,333745,4271,1,72600
2021-08-03,144.07,144.7,141.66,790270,141.9,144.07,144.08,113667175.993,143.8333,2,391695,4612,1,72600

### Historical Price Interday Summaries with some optional parameters  

Limit the response to past 20 days and also select a subset of the available fields

In [14]:
response = historical_pricing.summaries.Definition(
    universe = "VOD.L",
    interval = historical_pricing.Intervals.DAILY,          # Supported intervals: DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY.
    count = 10,
    fields = ["BID", "ASK", "OPEN_PRC", "HIGH_1", "LOW_1", "TRDPRC_1", "NUM_MOVES", "TRNOVR_UNS"]
).get_data()
# Extract in DataFrame format
response.data.df

,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
2021-07-21,115.1,115.12,113.46,115.34,113.0,115.1,12402,26106893124.500191
2021-07-22,116.02,116.04,115.54,117.34,115.28,116.04,14893,7608296291.4
2021-07-23,118.82,118.84,120.1,121.12,118.04,118.84,15868,11083755076.43568
2021-07-26,117.6,117.62,118.2,118.2,116.6,117.68,9873,9847874196.495411
2021-07-27,116.74,116.76,117.4,117.64,115.92,116.74,10371,4866924549.1
2021-07-28,115.34,115.38,116.76,117.08,115.22,115.6138,10579,5989022574.2078
2021-07-29,116.38,116.4,115.92,117.16,114.64,116.4,12130,10044526556.030001
2021-07-30,116.16,116.18,115.5,117.1,115.24,116.18,10834,5843621068.31329
2021-08-02,116.78,116.8,116.34,117.42,116.28,116.8,9377,5260777354.47331
2021-08-03,117.68,117.7,117.14,117.78,116.5,117.7,10106,5083126240.49195

### Close the session

In [15]:
close_session()

In [9]:
response.http_status

{'http_status_code': 400,
 'http_reason': 'Bad Request',
 'error': {'id': 'f86893b4-74e0-408b-961d-47955429c7a8',
  'code': 'TS.Intraday.UserRequestError.90004',
  'status': '400',
  'message': 'Request Validation Error',
  'errors': [{'key': 'start',
    'reason': 'The request parameter validation failed. start is invalid format.',
    'invalidValues': ['2021-08-03T10:33:35.554103+00:00000Z']}]}}

In [10]:
response.http_response