# Refinitiv Data Library for Python
## Content - Search, Lookup and View Metadata
This notebook demonstrates how to utilise the Search API using the Refinitiv Data Platform OR via Refinitiv Eikon/Workspace.

For more details on the Search API refer to the following:

* The article, [Building Search into your Application Workflow](https://developers.refinitiv.com/en/article-catalog/article/building-search-into-your-application-workflow), provides an overview of the capabilities of the Search service including tips and tricks and many useful techniques.

* Search API documentation: [Search Reference Guide](https://apidocs.refinitiv.com/Apps/ApiDocs#/details/L2Rpc2NvdmVyeS9zZWFyY2gvdjE=/Lw==/POST/README)

## Import the library and load credentials

Credentials used by this and the other tutorials notebooks are stored in the **Configuration/credentials.ipynb** file.     

You should have edited the **Configuration/credentials.ipynb** to set your credentials as part of the **Quick Start** step.

In [1]:
from refinitiv.data.content import search
import pandas as pd
import json

%run ../../Configuration/credentials.ipynb

## Open the session of your choice

Use our helper function in the Credentials notebook, **open_session(session_type)**, to create and open a session to connect to the 
- Refinitiv Data Platform directly (session_type="rdp") or via 
- Eikon 4 or Refinitiv Workspace (session_type="desktop")   

You can also set a default in the **credentials** notebook

**Note**: You cannot currently use the Search API via a Deployed session

In [2]:
open_session()

#### General Search

In [3]:
response = search.Definition("IBM Bonds").get_data()
response.data.df

,DocumentTitle,PI,RIC,BusinessEntity,PermID
0,"International Business Machines Corp, Plain Va...",0x00102c2565da06a0,US137584115=,INSTRUMENTxFIXEDINCOMExGOVCORP,46638470066
1,"International Business Machines Corp, Fixed Ma...",0x0004051b94d20854,459200HX2=,INSTRUMENTxFIXEDINCOMExGOVCORP,44657599150
2,"International Business Machines Corp, Plain Va...",0x00102c28b5f20b58,459200JQ5=,INSTRUMENTxFIXEDINCOMExGOVCORP,46642939296
3,"International Business Machines Corp, Plain Va...",0x00102c2452251a75,459200JX0=,INSTRUMENTxFIXEDINCOMExGOVCORP,192841929423
4,"International Business Machines Corp, Plain Va...",0x0004050e34388b88,459200HG9=,INSTRUMENTxFIXEDINCOMExGOVCORP,44640212240
5,"International Business Machines Corp, Plain Va...",0x00102c05c4dd0222,US127166528=,INSTRUMENTxFIXEDINCOMExGOVCORP,46635711098
6,"International Business Machines Corp, Plain Va...",0x00102c80bf6b046c,459200JC6=,INSTRUMENTxFIXEDINCOMExGOVCORP,46637038358
7,"International Business Machines Corp, Plain Va...",0x00102c53ff1f1897,US194445601=,INSTRUMENTxFIXEDINCOMExGOVCORP,192826899363
8,"International Business Machines Corp, Plain Va...",0x0004051bd47954e3,US114316318=,INSTRUMENTxFIXEDINCOMExGOVCORP,44657843041
9,"International Business Machines Corp, Plain Va...",0x00040513a4865c6c,459200HP9=,INSTRUMENTxFIXEDINCOMExGOVCORP,44649129642

#### Specify number of rows to fetch

In [4]:
response = search.Definition("IBM Bonds", top=100).get_data()
response.data.df

,DocumentTitle,PI,RIC,BusinessEntity,PermID
0,"International Business Machines Corp, Plain Va...",0x00102c2565da06a0,US137584115=,INSTRUMENTxFIXEDINCOMExGOVCORP,46638470066
1,"International Business Machines Corp, Fixed Ma...",0x0004051b94d20854,459200HX2=,INSTRUMENTxFIXEDINCOMExGOVCORP,44657599150
2,"International Business Machines Corp, Plain Va...",0x00102c28b5f20b58,459200JQ5=,INSTRUMENTxFIXEDINCOMExGOVCORP,46642939296
3,"International Business Machines Corp, Plain Va...",0x00102c2452251a75,459200JX0=,INSTRUMENTxFIXEDINCOMExGOVCORP,192841929423
4,"International Business Machines Corp, Plain Va...",0x0004050e34388b88,459200HG9=,INSTRUMENTxFIXEDINCOMExGOVCORP,44640212240
...,...,...,...,...,...
95,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",0x000034000037ecef,<NA>,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
96,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",0x000034000037edee,<NA>,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
97,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",0x000034000037eeed,<NA>,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
98,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",0x000034000037efec,<NA>,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
99,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",0x000034000037f0f3,<NA>,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>

#### Filter Expressions

In [5]:
response = search.Definition(
    view=search.SearchViews.GOV_CORP_INSTRUMENTS,
    select="ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate", 
    filter="IssuerTicker eq 'IBM' and IsActive eq true and AssetStatus ne 'MAT'"
).get_data()
response.data.df

,IssueDate,MaturityDate,CouponRate,Currency,RIC,FaceIssuedTotal,ISIN
0,2016-03-07T00:00:00.000Z,2021-09-07T00:00:00.000Z,0.5,EUR,US137584115=,1000000000,XS1375841159
1,2014-11-06T00:00:00.000Z,2021-11-06T00:00:00.000Z,0.75538,USD,459200HX2=,1100000000,US459200HX26
2,2017-01-27T00:00:00.000Z,2022-01-27T00:00:00.000Z,2.5,USD,459200JQ5=,1000000000,US459200JQ56
3,2019-05-15T00:00:00.000Z,2022-05-13T00:00:00.000Z,2.85,USD,459200JX0=,2750000000,US459200JX08
4,2012-07-30T00:00:00.000Z,2022-08-01T00:00:00.000Z,1.875,USD,459200HG9=,1000000000,US459200HG92
5,2015-08-05T00:00:00.000Z,2022-08-05T00:00:00.000Z,2.625,GBP,US127166528=,300000000,XS1271665280
6,2015-11-09T00:00:00.000Z,2022-11-09T00:00:00.000Z,2.875,USD,459200JC6=,900000000,US459200JC60
7,2019-01-31T00:00:00.000Z,2023-01-31T00:00:00.000Z,0.375,EUR,US194445601=,1750000000,XS1944456018
8,2014-11-26T00:00:00.000Z,2023-05-26T00:00:00.000Z,1.25,EUR,US114316318=,1000000000,XS1143163183
9,2013-08-01T00:00:00.000Z,2023-08-01T00:00:00.000Z,3.375,USD,459200HP9=,1500000000,US459200HP91

#### Properties - Metadata

In [6]:
response = search.metadata.Definition(
    view = search.SearchViews.GOV_CORP_INSTRUMENTS  # Required parameterc
).get_data()

# for Pandas Display purpose only
pd.set_option("display.max_columns", None) 
pd.set_option("display.max_rows", 10)  # Just show 10 rows
pd.set_option("display.max_colwidth", 1)  

response.data.df

,,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AccrualDate,AccrualDate,Date,True,True,True,False,False,False
AccruedInterest,AccruedInterest,Double,True,True,True,False,False,False
ActiveEstimatesExist,ActiveEstimatesExist,Boolean,True,False,False,False,False,False
AdtLocalCurrencyValue,AdtLocalCurrencyValue,String,True,False,False,False,False,False
AdtLocalCurrencyValueName,AdtLocalCurrencyValueName,String,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...
WorstStandardYield,WorstStandardYield,Double,True,True,True,False,False,False
WorstYearsToRedem,WorstYearsToRedem,Double,True,True,True,False,False,False
YieldCurveBenchmarkRIC,YieldCurveBenchmarkRIC,String,False,False,False,False,False,False
YieldTypeDescription,YieldTypeDescription,String,True,False,False,False,False,False
ZCodeValue,ZCodeValue,String,True,True,False,False,False,True

#### Navigators

In [7]:
response = search.Definition(
    top=0,
    navigators="RCSTRBC2012Leaf"
).get_data()

#### Response Data Structure

In [8]:
# Check if request was successful
if (response.is_success):
    # Should have raw data when is_success==true
    if response.data.raw:
        display(response.data.raw)
    else:
        print("Response does not contain raw data")    
    # Check if the response contains a Dataframe too?
    if (not response.data.df.empty):
        display(response.data.df)
    else:
        print("\nResponse does not contain DataFrame")
else: 
    # Something went wrong
    print(f"Not Sucessful : {response.http_status}")

{'Total': 150511573,
 'Hits': [],
 'Navigators': {'RCSTRBC2012Leaf': {'Buckets': [{'Label': 'Banks (NEC)',
     'Count': 3714914},
    {'Label': 'Corporate Financial Services (NEC)', 'Count': 2883235},
    {'Label': 'Corporate Banks', 'Count': 1472765},
    {'Label': 'Retail & Mortgage Banks', 'Count': 1298308},
    {'Label': 'Public Finance Activities', 'Count': 790716},
    {'Label': 'Investment Banking & Brokerage Services (NEC)',
     'Count': 688649},
    {'Label': 'Investment Management & Fund Operators (NEC)', 'Count': 382989},
    {'Label': 'Consumer Lending (NEC)', 'Count': 356504},
    {'Label': 'Electric Utilities (NEC)', 'Count': 308771},
    {'Label': 'Diversified Investment Services', 'Count': 291410},
    {'Label': 'Investment Holding Companies (NEC)', 'Count': 281533},
    {'Label': 'Professional Information Services (NEC)', 'Count': 278018},
    {'Label': 'Wealth Management', 'Count': 272767},
    {'Label': 'Construction & Engineering (NEC)', 'Count': 252591},
    {'Label': 'Real Estate Rental, Development & Operations (NEC)',
     'Count': 250200},
    {'Label': 'Business Support Services (NEC)', 'Count': 228989},
    {'Label': 'Building Contractors', 'Count': 202221},
    {'Label': 'Financial & Commodity Market Operators & Service Providers (NEC)',
     'Count': 182439},
    {'Label': 'Government & Government Finance (NEC)', 'Count': 182344},
    {'Label': 'Management Consulting Services', 'Count': 164337},
    {'Label': 'Investment Banking', 'Count': 150020},
    {'Label': 'Software (NEC)', 'Count': 133003},
    {'Label': 'IT Services & Consulting (NEC)', 'Count': 131749},
    {'Label': 'UK Investment Trusts', 'Count': 131456},
    {'Label': 'Real Estate Services (NEC)', 'Count': 113720},
    {'Label': 'Investment Management', 'Count': 102918},
    {'Label': 'Consumer Leasing', 'Count': 101661},
    {'Label': 'Hedge Funds', 'Count': 97993},
    {'Label': 'Supermarkets & Convenience Stores', 'Count': 97092},
    {'Label': 'Pharmaceuticals (NEC)', 'Count': 95881},
    {'Label': 'Integrated Telecommunications Services (NEC)', 'Count': 92086},
    {'Label': 'Oil & Gas Exploration and Production (NEC)', 'Count': 85745},
    {'Label': 'Hospitals, Clinics & Primary Care Services', 'Count': 83800},
    {'Label': 'Brokerage Services', 'Count': 82654},
    {'Label': 'Industrial Machinery & Equipment (NEC)', 'Count': 81431},
    {'Label': 'Commodity Chemicals (NEC)', 'Count': 79293},
    {'Label': 'Insurance Brokers', 'Count': 74627},
    {'Label': 'Food Processing (NEC)', 'Count': 73164},
    {'Label': 'Auto Vehicles, Parts & Service Retailers (NEC)',
     'Count': 72754},
    {'Label': 'Restaurants & Bars (NEC)', 'Count': 68057},
    {'Label': 'Industrial Machinery', 'Count': 64364},
    {'Label': 'Residential Builders - Single Homes', 'Count': 63042},
    {'Label': 'Miscellaneous Educational Service Providers', 'Count': 61753},
    {'Label': 'Construction Materials (NEC)', 'Count': 59875},
    {'Label': 'Multiline Utilities', 'Count': 58611},
    {'Label': 'Electrical Components & Equipment (NEC)', 'Count': 57966},
    {'Label': 'Auto, Truck & Motorcycle Parts (NEC)', 'Count': 55541},
    {'Label': 'Government Administration Activities', 'Count': 55328},
    {'Label': 'Closed End Funds', 'Count': 55074},
    {'Label': 'Hotels & Motels', 'Count': 54017},
    {'Label': 'Land Division & Subdivision', 'Count': 52960},
    {'Label': 'Freight Trucking', 'Count': 51676},
    {'Label': 'Biotechnology & Medical Research (NEC)', 'Count': 50968},
    {'Label': 'Consumer Goods Conglomerates', 'Count': 50352},
    {'Label': 'Shell Companies', 'Count': 50313},
    {'Label': 'Commercial Loans', 'Count': 49491},
    {'Label': 'Highway & Bridge Construction', 'Count': 48982},
    {'Label': 'Civil Engineers & Architects', 'Count': 48493},
    {'Label': 'Life & Health Insurance (NEC)', 'Count': 48121},
    {'Label': 'Oil & Gas Refining and Marketing (NEC)', 'Count': 47538},
    {'Label': 'Plastics', 'Count': 47252},
    {'Label': 'Iron & Steel (NEC)', 'Count': 47046},
    {'Label': 'Auto & Truck Manufacturers (NEC)', 'Count': 46633},
    {'Label': 'Metallic Rolling & Drawing Products', 'Count': 46267},
    {'Label': 'Personal Services (NEC)', 'Count': 45648},
    {'Label': 'Drug Retailers (NEC)', 'Count': 43155},
    {'Label': 'Plumbing Fixtures & Fittings', 'Count': 42949},
    {'Label': 'Office Real Estate Rental & Development', 'Count': 42838},
    {'Label': 'Healthcare Facilities & Services (NEC)', 'Count': 42529},
    {'Label': 'Oil & Gas Transportation Services (NEC)', 'Count': 40498},
    {'Label': 'Diversified Mining', 'Count': 39701},
    {'Label': 'Wireless Telecommunications Services (NEC)', 'Count': 39100},
    {'Label': 'Passenger Transportation, Ground & Sea (NEC)', 'Count': 37876},
    {'Label': 'Semiconductors (NEC)', 'Count': 37615},
    {'Label': 'Homebuilding (NEC)', 'Count': 37530},
    {'Label': 'Maintenance & Repair Services', 'Count': 37478},
    {'Label': 'Gasoline Stations', 'Count': 37209},
    {'Label': 'Waste Management, Disposal & Recycling Services',
     'Count': 35836},
    {'Label': 'Property & Casualty Insurance (NEC)', 'Count': 35570},
    {'Label': 'Legal Services', 'Count': 35325},
    {'Label': 'Medical Equipment, Supplies & Distribution (NEC)',
     'Count': 34656},
    {'Label': 'Commercial Leasing', 'Count': 34553},
    {'Label': 'Residential Real Estate Rental & Development', 'Count': 34545},
    {'Label': 'Petroleum Refining', 'Count': 34095},
    {'Label': 'Commercial Buildings', 'Count': 33455},
    {'Label': 'Coal (NEC)', 'Count': 32567},
    {'Label': 'Private Banks', 'Count': 32417},
    {'Label': 'Freight Logistics', 'Count': 32148},
    {'Label': 'Natural Gas Utilities (NEC)', 'Count': 32084},
    {'Label': 'Broadcasting (NEC)', 'Count': 32067},
    {'Label': 'Cement & Concrete Manufacturing', 'Count': 31988},
    {'Label': 'Commercial REITs (NEC)', 'Count': 31827},
    {'Label': 'Child Care & Family Services', 'Count': 31049},
    {'Label': 'Advertising Agency', 'Count': 30846},
    {'Label': 'Personal Products (NEC)', 'Count': 30818},
    {'Label': 'Bio Therapeutic Drugs', 'Count': 30789},
    {'Label': 'Food Retail & Distribution (NEC)', 'Count': 30578},
    {'Label': 'Gold Mining', 'Count': 30381},
    {'Label': 'Industrial Equipment Rental', 'Count': 30204},
    {'Label': 'Personal & Car Loans', 'Count': 30191}]}}}

Response does not contain DataFrame

#### Search with Navigator option

In [9]:
response = search.Definition(
    view=search.SearchViews.COMMODITY_QUOTES,
    query="cheese",
    navigators="ExchangeName"
).get_data()

response.data.df

,DocumentTitle,PI,RIC,BusinessEntity,PermID
0,"CME Cash Settled Cheese Electronic Commodity Future Continuation 1, Commodity Future, Chicago Mercantile Exchange",273610776,CSCc1,QUOTExCOMMODITY,21622940491
1,"CME Cash Settled Cheese Electronic Commodity Future Jul 2021, Commodity Future, Chicago Mercantile Exchange",379195159,CSCN1,QUOTExCOMMODITY,21705602183
2,"CME Cash Settled Cheese Electronic Commodity Future Aug 2021, Commodity Future, Chicago Mercantile Exchange",384919875,CSCQ1,QUOTExCOMMODITY,21710249450
3,"CME Cash Settled Cheese Electronic Commodity Future Sep 2021, Commodity Future, Chicago Mercantile Exchange",390497653,CSCU1,QUOTExCOMMODITY,21714572907
4,"CME Cash Settled Cheese Electronic Commodity Future Oct 2021, Commodity Future, Chicago Mercantile Exchange",396055563,CSCV1,QUOTExCOMMODITY,21718846354
5,"CME Cash Settled Cheese Electronic Commodity Future Nov 2021, Commodity Future, Chicago Mercantile Exchange",402256891,CSCX1,QUOTExCOMMODITY,21723899060
6,"CME Cash Settled Cheese Electronic Commodity Future Jun 2021, Commodity Future, Chicago Mercantile Exchange",374717665,CSCM1,QUOTExCOMMODITY,21701993019
7,"CME Cash Settled Cheese Electronic Commodity Future Dec 2021, Commodity Future, Chicago Mercantile Exchange",406809544,CSCZ1,QUOTExCOMMODITY,21727643040
8,"CME Cash Settled Cheese Electronic Commodity Future Jan 2022, Commodity Future, Chicago Mercantile Exchange",413501786,CSCF2,QUOTExCOMMODITY,21733097271
9,"CME Cash Settled Cheese Electronic Commodity Future Feb 2022, Commodity Future, Chicago Mercantile Exchange",419119906,CSCG2,QUOTExCOMMODITY,21737604992

In [10]:
response.data.raw["Navigators"]['ExchangeName']

{'Buckets': [{'Label': 'CME:Index and Options Market', 'Count': 18994},
  {'Label': 'Chicago Mercantile Exchange', 'Count': 5522},
  {'Label': 'INTL FCStone Inc', 'Count': 2550},
  {'Label': 'Source is a Refinitiv Contributor', 'Count': 1498},
  {'Label': 'US Department of Agriculture', 'Count': 93},
  {'Label': 'Commodity Futures Trading Commission', 'Count': 66},
  {'Label': 'Complete Intelligence', 'Count': 37},
  {'Label': 'Intercontinental Exchange US', 'Count': 31},
  {'Label': 'US Bureau Of Labor Statistics', 'Count': 10},
  {'Label': 'DCA Markets B.V. - DCA-Markets-PRA Price Reporting Agent',
   'Count': 4},
  {'Label': 'European Energy Exchange', 'Count': 4},
  {'Label': 'European Commission', 'Count': 3},
  {'Label': 'ESALQ', 'Count': 2},
  {'Label': 'CME:International Monetary Market', 'Count': 1}]}

In [10]:
response = search.Definition(
    view=search.SearchViews.GOV_CORP_INSTRUMENTS,
    top=0,
    navigators="Currency(buckets:10,desc:sum_FaceOutstandingUSD,calc:max_CouponRate)"
).get_data()

response.data.raw

{'Total': 8235649,
 'Hits': [],
 'Navigators': {'Currency': {'Buckets': [{'Label': 'USD',
     'Count': 3385504,
     'max_CouponRate': 1800.0,
     'sum_FaceOutstandingUSD': 47506065838786.0},
    {'Label': 'EUR',
     'Count': 1017451,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 23956237006860.0},
    {'Label': 'CNY',
     'Count': 280131,
     'max_CouponRate': 72.0,
     'sum_FaceOutstandingUSD': 18101827306169.0},
    {'Label': 'JPY',
     'Count': 422559,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 12977062833090.018},
    {'Label': 'GBP',
     'Count': 178768,
     'max_CouponRate': 120.0,
     'sum_FaceOutstandingUSD': 4718608035205.0},
    {'Label': 'INR',
     'Count': 102791,
     'max_CouponRate': 42.75,
     'sum_FaceOutstandingUSD': 2579149481552.0},
    {'Label': 'CAD',
     'Count': 292893,
     'max_CouponRate': 100.0,
     'sum_FaceOutstandingUSD': 2556928542073.0},
    {'Label': 'KRW',
     'Count': 373896,
     'max_CouponRate': 42.0,
     'sum_FaceOutstandingUSD': 2346619797678.5986},
    {'Label': 'AUD',
     'Count': 129352,
     'max_CouponRate': 120.96,
     'sum_FaceOutstandingUSD': 1573638364824.7576},
    {'Label': 'BRL',
     'Count': 41067,
     'max_CouponRate': 108.5,
     'sum_FaceOutstandingUSD': 917440664293.0034}]}}}

#### Sub-navigator

In [11]:
response = search.Definition(
    view=search.SearchViews.PEOPLE,
    top=0,
    navigators="FirstName(buckets:3,sub:LastName(buckets:2))"
).get_data()

response.data.raw["Navigators"]["FirstName"]["Buckets"]

[{'Label': 'John',
  'Count': 39165,
  'LastName': {'Buckets': [{'Label': 'Murphy', 'Count': 103},
    {'Label': 'Lee', 'Count': 101}]}},
 {'Label': 'David',
  'Count': 37637,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 225},
    {'Label': 'Williams', 'Count': 152}]}},
 {'Label': 'Michael',
  'Count': 36341,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 179},
    {'Label': 'Brown', 'Count': 117}]}}]

#### Search with order_by option

In [12]:
response = search.Definition(
    view=search.SearchViews.PEOPLE,
    query="ceo",
    order_by="YearOfBirth desc,LastName,FirstName",
    select="YearOfBirth,DocumentTitle"
).get_data()

response.data.df

,YearOfBirth,DocumentTitle
0,1996,"Shu Yao - Dongjiang Environmental Co Ltd - Ex-Chief Executive Officer, Executive Director"
1,1992,Christian Besenbruch - Deep Render Ltd - Chief Executive Officer and Co-Founder
2,1992,"Ivan Aleksandrovich Plekhanov - Territorial'naya Generiruyushchaya Kompaniya No2 PAO - Executive Director, Adviser to General Director (CEO)"
3,1991,"Grigory Sergeevich Sandulov - Omskiy Rechnoy Port AO - General Director (CEO), Director"
4,1991,Yehonatan Shachar - Upsellon Brands Holdings Ltd - Chief Executive Officer
5,1990,"Myeong Jin Chae - Arion Technology Inc - Chief Executive Officer, Director"
6,1990,"Pedro de Godoy Bueno - Diagnosticos da America SA - Chief Executive Officer, Director"
7,1990,"Hikaru Ohno - Cyber Security Cloud Inc - President, Chief Executive Officer, Representative Director"
8,1990,Nigel Phan - Whirli Ltd - Chief Executive Officer
9,1990,"Harrison Woods - Yourparkingspace Ltd - Chief Executive Officer, Co-Founder"

#### Search with group_by option

In [13]:
response = search.Definition(
    view=search.SearchViews.INDICATOR_QUOTES,
    query="rate",
    group_by="CentralBankName",
    group_count=2,
    select="CentralBankName,DocumentTitle,RIC"
).get_data()

response.data.df

,CentralBankName,DocumentTitle,RIC
0,Federal Reserve System,"United States, Policy Rates, Fed Funds Target Rate, Reuters Polls, Daily, The Federal Open Market Committee",USFOMC=ECI
1,Federal Reserve System,"United States, Policy Rates, Fed Overnight Repo, Reuters Polls, Daily, Federal Reserve, United States",USRRP=ECI
2,Bank of England,"United Kingdom, Policy Rates, Bank Rate, Reuters Polls, Monthly, Bank of England",GBBOEI=ECI
3,Bank of England,"United Kingdom, BOE Bank Rate-Median, Reuters Polls, Monthly, Reuters",pGBBOEI=M
4,European Central Bank,"Euro Zone, Policy Rates, ECB Main refinancing, Fixed Rate (Announcement Dates), Reuters Polls, Monthly, ECB - European Central Bank",EUECBR=ECI
5,European Central Bank,"Euro Zone, Policy Rates, ECB Deposit Rate, Reuters Polls, Monthly, ECB - European Central Bank",EUECBD=ECI
6,Banco de Mexico,"Mexico, Policy Rates, Reference Rate (Overnight Lending Rate), Reuters Polls, Monthly, Banco de Mexico",MXCBIR=ECI
7,Banco de Mexico,"Mexico, Interest Rate-Low, Reuters Polls, Monthly, Reuters",pMXCBIR=L
8,Bank of Mauritius,"Mauritius, Policy Rates, Key Repo Rate, Reuters Polls, Quarterly, Bank of Mauritius",MUCBIR=ECI
9,Czech National Bank,"Czech Republic, Policy Rates, Repo Rate (2 Week), Reuters Polls, Daily, CNB - Czech National Bank",CZCBIR=ECI

#### Search For People

In [14]:
response = search.Definition(
    query="cfo",
    view=search.SearchViews.PEOPLE
).get_data()

response.data.df

,PI,BusinessEntity,DocumentTitle,PermID
0,34415553383,PERSON,"Amy E. Hood - Microsoft Corp - Chief Financial Officer, Executive Vice President",34415553383
1,34414554748,PERSON,"Luca Maestri - Apple Inc - Chief Financial Officer, Senior Vice President",34414554748
2,34417610894,PERSON,"Brian T. Olsavsky - Amazon.com Inc - Chief Financial Officer, Senior Vice President",34417610894
3,34413960665,PERSON,"Ruth M. Porat - Alphabet Inc - Chief Financial Officer, Senior Vice President",34413960665
4,34414804241,PERSON,David M. Wehner - Facebook Inc - Chief Financial Officer,34414804241
5,34413152672,PERSON,"Marc D. Hamburg - Berkshire Hathaway Inc - Chief Financial Officer, Senior Vice President",34413152672
6,34414966250,PERSON,Andrew K. Klatt - Berkshire Hathaway Inc - CFO & COO,34414966250
7,34414263702,PERSON,Maggie Wu - Alibaba Group Holding Ltd - Chief Financial Officer and Head of Strategic Investments,34414263702
8,34414907131,PERSON,"John Lo - Tencent Holdings Ltd - Chief Financial Officer, Senior Vice President",34414907131
9,34413340523,PERSON,"Vasant M. Prabhu - Visa Inc - Vice Chairman of the Board, Chief Financial Officer",34413340523

### Lookup

In [15]:
response = search.lookup.Definition(
    view=search.SearchViews.INSTRUMENTS,                               # Required parameter
    scope="RIC",                                                       # Required parameter
    terms="MSFT.O,AAPL.O,GOOG.O,IBM.N,KBANK.BK,SCC.BK",                # Required parameter
    select="BusinessEntity,DocumentTitle,CUSIP,SEDOL",                 # Required parameter
).get_data()

response.data.df

,BusinessEntity,CUSIP,DocumentTitle,SEDOL
MSFT.O,INSTRUMENTxEQUITY,594918104,"Microsoft Corp, Ordinary Share",<NA>
AAPL.O,INSTRUMENTxEQUITY,037833100,"Apple Inc, Ordinary Share",<NA>
GOOG.O,INSTRUMENTxEQUITY,02079K107,"Alphabet Inc, Ordinary Share",<NA>
KBANK.BK,INSTRUMENTxEQUITY,<NA>,"Kasikornbank PCL, Ordinary Share",6888783
SCC.BK,INSTRUMENTxEQUITY,<NA>,"Siam Cement PCL, Ordinary Share",6609917

In [18]:
response = search.lookup.Definition(
    view=search.SearchViews.SEARCH_ALL,                              # Required parameter
    scope="RIC",                                                     # Required parameter
    terms="A,B,NOSUCHRIC,C,D",                                       # Required parameter
    select="BusinessEntity,DocumentTitle",                           # Required parameter
).get_data()

response.data.df

  BusinessEntity                                                DocumentTitle
A  QUOTExEQUITY   Agilent Technologies Inc, Ordinary Share, NYSE Consolidated
B  QUOTExEQUITY   Barnes Group Inc, Ordinary Share, NYSE Consolidated
C  QUOTExEQUITY   Citigroup Inc, Ordinary Share, NYSE Consolidated
D  QUOTExEQUITY   Dominion Energy Inc, Ordinary Share, NYSE Consolidated

## Close the session

In [16]:
close_session()