# Refinitiv Data Library for Python
## Content - Search, Lookup and View Metadata
This notebook demonstrates how to utilise the Search API using the Refinitiv Data Platform OR via Refinitiv Eikon/Workspace.

For more details on the Search API refer to the following:

* The article, [Building Search into your Application Workflow](https://developers.refinitiv.com/en/article-catalog/article/building-search-into-your-application-workflow), provides an overview of the capabilities of the Search service including tips and tricks and many useful techniques.

* Search API documentation: [Search Reference Guide](https://apidocs.refinitiv.com/Apps/ApiDocs#/details/L2Rpc2NvdmVyeS9zZWFyY2gvdjE=/Lw==/POST/README)

## Set the location of the configuration file
For ease of use, you can set various initialization parameters of the RD Library in the **_refinitiv-data.config.json_** configuration file - as described in the Quick Start -> Sessions example.

### One config file for the tutorials
As these tutorial Notebooks are categorised into sub-folders and to avoid the need for multiple config files, we will use the _RD_LIB_CONFIG_PATH_ environment variable to point to a single instance of the config file in the top-level ***Configuration*** folder.

Before proceeding, please **ensure you have entered your credentials** into the config file in the ***Configuration*** folder.

In [1]:
import os
os.environ["RD_LIB_CONFIG_PATH"] = "../../../Configuration"

In [2]:
from refinitiv.data.content import search
import refinitiv.data as rd
import pandas as pd
import json

## Open the default session

To open the default session ensure you have a '*refinitiv-data.config.json*' in the ***Configuration*** directory, populated with your credentials and specified a 'default' session in the config file

In [3]:
rd.open_session()

#### General Search

In [4]:
response = search.Definition("IBM Bonds").get_data()
response.data.df

,DocumentTitle,BusinessEntity,PI,RIC,PermID
0,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c28b5f20b58,459200JQ5=,46642939296
1,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c2452251a75,459200JX0=,192841929423
2,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x0004050e34388b88,459200HG9=,44640212240
3,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c05c4dd0222,US127166528=,46635711098
4,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c80bf6b046c,459200JC6=,46637038358
5,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c53ff1f1897,US194445601=,192826899363
6,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x0004051bd47954e3,US114316318=,44657843041
7,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00040513a4865c6c,459200HP9=,44649129642
8,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00040517bba31719,459200HU8=,44653695161
9,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c2052251a71,459200JY8=,192841929400

#### Specify number of rows to fetch

In [5]:
response = search.Definition("IBM Bonds", top=100).get_data()
response.data.df

,DocumentTitle,BusinessEntity,PI,RIC,PermID
0,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c28b5f20b58,459200JQ5=,46642939296
1,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c2452251a75,459200JX0=,192841929423
2,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x0004050e34388b88,459200HG9=,44640212240
3,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c05c4dd0222,US127166528=,46635711098
4,"International Business Machines Corp, Plain Va...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x00102c80bf6b046c,459200JC6=,46637038358
...,...,...,...,...,...
95,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x000034000037e3e0,<NA>,<NA>
96,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x000034000037e4e7,<NA>,<NA>
97,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x000034000037e5e6,<NA>,<NA>
98,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x000034000037e6e5,<NA>,<NA>
99,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",INSTRUMENTxFIXEDINCOMExGOVCORP,0x000034000037e7e4,<NA>,<NA>

#### Filter Expressions

In [6]:
response = search.Definition(
    view=search.SearchViews.GOV_CORP_INSTRUMENTS,
    select="ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate", 
    filter="IssuerTicker eq 'IBM' and IsActive eq true and AssetStatus ne 'MAT'"
).get_data()
response.data.df

,FaceIssuedTotal,IssueDate,CouponRate,MaturityDate,ISIN,Currency,RIC
0,1000000000,2017-01-27T00:00:00.000Z,2.5,2022-01-27T00:00:00.000Z,US459200JQ56,USD,459200JQ5=
1,2750000000,2019-05-15T00:00:00.000Z,2.85,2022-05-13T00:00:00.000Z,US459200JX08,USD,459200JX0=
2,1000000000,2012-07-30T00:00:00.000Z,1.875,2022-08-01T00:00:00.000Z,US459200HG92,USD,459200HG9=
3,300000000,2015-08-05T00:00:00.000Z,2.625,2022-08-05T00:00:00.000Z,XS1271665280,GBP,US127166528=
4,900000000,2015-11-09T00:00:00.000Z,2.875,2022-11-09T00:00:00.000Z,US459200JC60,USD,459200JC6=
5,1750000000,2019-01-31T00:00:00.000Z,0.375,2023-01-31T00:00:00.000Z,XS1944456018,EUR,US194445601=
6,1000000000,2014-11-26T00:00:00.000Z,1.25,2023-05-26T00:00:00.000Z,XS1143163183,EUR,US114316318=
7,1500000000,2013-08-01T00:00:00.000Z,3.375,2023-08-01T00:00:00.000Z,US459200HP91,USD,459200HP9=
8,2000000000,2014-02-12T00:00:00.000Z,3.625,2024-02-12T00:00:00.000Z,US459200HU86,USD,459200HU8=
9,3000000000,2019-05-15T00:00:00.000Z,3.0,2024-05-15T00:00:00.000Z,US459200JY80,USD,459200JY8=

#### Properties - Metadata

In [7]:
response = search.metadata.Definition(
    view = search.SearchViews.GOV_CORP_INSTRUMENTS  # Required parameterc
).get_data()

# for Pandas Display purpose only
pd.set_option("display.max_columns", None) 
pd.set_option("display.max_rows", 10)  # Just show 10 rows
pd.set_option("display.max_colwidth", 1)  

response.data.df

,,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AccrualDate,AccrualDate,Date,True,True,True,False,False,False
AccruedInterest,AccruedInterest,Double,True,True,True,False,False,False
ActiveEstimatesExist,ActiveEstimatesExist,Boolean,True,False,False,False,False,False
AdtLocalCurrencyValue,AdtLocalCurrencyValue,String,True,False,False,False,False,False
AdtLocalCurrencyValueName,AdtLocalCurrencyValueName,String,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...
WorstStandardYield,WorstStandardYield,Double,True,True,True,False,False,False
WorstYearsToRedem,WorstYearsToRedem,Double,True,True,True,False,False,False
YieldCurveBenchmarkRIC,YieldCurveBenchmarkRIC,String,False,False,False,False,False,False
YieldTypeDescription,YieldTypeDescription,String,True,False,False,False,False,False
ZCodeValue,ZCodeValue,String,True,True,False,False,False,True

#### Navigators

In [8]:
response = search.Definition(
    top=0,
    navigators="RCSTRBC2012Leaf"
).get_data()

#### Response Data Structure

In [9]:
# Should have raw data when is_success==true
if response.data.raw:
    display(response.data.raw)
else:
    print("Response does not contain raw data")    
# Check if the response contains a Dataframe too?
if (not response.data.df.empty):
    display(response.data.df)
else:
    print("\nResponse does not contain DataFrame")

{'Total': 156960683,
 'Hits': [],
 'Navigators': {'RCSTRBC2012Leaf': {'Buckets': [{'Label': 'Banks (NEC)',
     'Count': 4100141},
    {'Label': 'Corporate Financial Services (NEC)', 'Count': 3014565},
    {'Label': 'Corporate Banks', 'Count': 1453001},
    {'Label': 'Retail & Mortgage Banks', 'Count': 1281362},
    {'Label': 'Investment Banking & Brokerage Services (NEC)',
     'Count': 704731},
    {'Label': 'Public Finance Activities', 'Count': 657542},
    {'Label': 'Consumer Lending (NEC)', 'Count': 404637},
    {'Label': 'Government & Government Finance (NEC)', 'Count': 361781},
    {'Label': 'Investment Management & Fund Operators (NEC)', 'Count': 338333},
    {'Label': 'Investment Holding Companies (NEC)', 'Count': 307643},
    {'Label': 'Electric Utilities (NEC)', 'Count': 299076},
    {'Label': 'Wealth Management', 'Count': 294659},
    {'Label': 'Diversified Investment Services', 'Count': 288961},
    {'Label': 'Construction & Engineering (NEC)', 'Count': 281071},
    {'Label': 'Professional Information Services (NEC)', 'Count': 278449},
    {'Label': 'Real Estate Rental, Development & Operations (NEC)',
     'Count': 264218},
    {'Label': 'Business Support Services (NEC)', 'Count': 240324},
    {'Label': 'Building Contractors', 'Count': 195744},
    {'Label': 'Financial & Commodity Market Operators & Service Providers (NEC)',
     'Count': 181893},
    {'Label': 'Investment Banking', 'Count': 179515},
    {'Label': 'Management Consulting Services', 'Count': 160751},
    {'Label': 'Software (NEC)', 'Count': 137519},
    {'Label': 'IT Services & Consulting (NEC)', 'Count': 133336},
    {'Label': 'Investment Management', 'Count': 129795},
    {'Label': 'Hedge Funds', 'Count': 108520},
    {'Label': 'Real Estate Services (NEC)', 'Count': 103820},
    {'Label': 'Pharmaceuticals (NEC)', 'Count': 100939},
    {'Label': 'Supermarkets & Convenience Stores', 'Count': 98920},
    {'Label': 'Integrated Telecommunications Services (NEC)', 'Count': 97091},
    {'Label': 'Government Administration Activities', 'Count': 95996},
    {'Label': 'UK Investment Trusts', 'Count': 90502},
    {'Label': 'Oil & Gas Exploration and Production (NEC)', 'Count': 87180},
    {'Label': 'Brokerage Services', 'Count': 85983},
    {'Label': 'Consumer Leasing', 'Count': 85805},
    {'Label': 'Industrial Machinery & Equipment (NEC)', 'Count': 84653},
    {'Label': 'Commodity Chemicals (NEC)', 'Count': 81186},
    {'Label': 'Hospitals, Clinics & Primary Care Services', 'Count': 80715},
    {'Label': 'Food Processing (NEC)', 'Count': 77233},
    {'Label': 'Insurance Brokers', 'Count': 75557},
    {'Label': 'Auto Vehicles, Parts & Service Retailers (NEC)',
     'Count': 72240},
    {'Label': 'Restaurants & Bars (NEC)', 'Count': 68806},
    {'Label': 'Multiline Utilities', 'Count': 60959},
    {'Label': 'Construction Materials (NEC)', 'Count': 59526},
    {'Label': 'Industrial Machinery', 'Count': 58634},
    {'Label': 'Auto, Truck & Motorcycle Parts (NEC)', 'Count': 57374},
    {'Label': 'Shell Companies', 'Count': 56881},
    {'Label': 'Electrical Components & Equipment (NEC)', 'Count': 56577},
    {'Label': 'Office Real Estate Rental & Development', 'Count': 55278},
    {'Label': 'Miscellaneous Educational Service Providers', 'Count': 53638},
    {'Label': 'Hotels & Motels', 'Count': 53349},
    {'Label': 'Biotechnology & Medical Research (NEC)', 'Count': 53065},
    {'Label': 'Closed End Funds', 'Count': 52901},
    {'Label': 'Freight Trucking', 'Count': 52759},
    {'Label': 'Land Division & Subdivision', 'Count': 51036},
    {'Label': 'Iron & Steel (NEC)', 'Count': 49823},
    {'Label': 'Oil & Gas Refining and Marketing (NEC)', 'Count': 49272},
    {'Label': 'Life & Health Insurance (NEC)', 'Count': 48925},
    {'Label': 'Residential Builders - Single Homes', 'Count': 48612},
    {'Label': 'Highway & Bridge Construction', 'Count': 46787},
    {'Label': 'Consumer Goods Conglomerates', 'Count': 45913},
    {'Label': 'Healthcare Facilities & Services (NEC)', 'Count': 45526},
    {'Label': 'Plastics', 'Count': 44996},
    {'Label': 'Metallic Rolling & Drawing Products', 'Count': 44777},
    {'Label': 'Drug Retailers (NEC)', 'Count': 43323},
    {'Label': 'Plumbing Fixtures & Fittings', 'Count': 42938},
    {'Label': 'Personal Services (NEC)', 'Count': 42937},
    {'Label': 'Civil Engineers & Architects', 'Count': 42587},
    {'Label': 'Diversified Mining', 'Count': 42345},
    {'Label': 'Oil & Gas Transportation Services (NEC)', 'Count': 41652},
    {'Label': 'Wireless Telecommunications Services (NEC)', 'Count': 40367},
    {'Label': 'Passenger Transportation, Ground & Sea (NEC)', 'Count': 39561},
    {'Label': 'Commercial Loans', 'Count': 39180},
    {'Label': 'Semiconductors (NEC)', 'Count': 39122},
    {'Label': 'Commercial Leasing', 'Count': 39084},
    {'Label': 'Petroleum Refining', 'Count': 38179},
    {'Label': 'Gasoline Stations', 'Count': 37257},
    {'Label': 'Property & Casualty Insurance (NEC)', 'Count': 37156},
    {'Label': 'Maintenance & Repair Services', 'Count': 37029},
    {'Label': 'Auto & Truck Manufacturers (NEC)', 'Count': 36965},
    {'Label': 'Medical Equipment, Supplies & Distribution (NEC)',
     'Count': 36884},
    {'Label': 'Coal (NEC)', 'Count': 36267},
    {'Label': 'Homebuilding (NEC)', 'Count': 36108},
    {'Label': 'Waste Management, Disposal & Recycling Services',
     'Count': 35934},
    {'Label': 'Residential Real Estate Rental & Development', 'Count': 35853},
    {'Label': 'Legal Services', 'Count': 35642},
    {'Label': 'Personal Products (NEC)', 'Count': 34433},
    {'Label': 'Broadcasting (NEC)', 'Count': 34026},
    {'Label': 'Commercial REITs (NEC)', 'Count': 33730},
    {'Label': 'Ground Freight & Logistics (NEC)', 'Count': 33673},
    {'Label': 'Commercial Buildings', 'Count': 33546},
    {'Label': 'Bio Therapeutic Drugs', 'Count': 32231},
    {'Label': 'Cement & Concrete Manufacturing', 'Count': 32180},
    {'Label': 'Food Retail & Distribution (NEC)', 'Count': 31924},
    {'Label': 'Gold Mining', 'Count': 31652},
    {'Label': 'Natural Gas Utilities (NEC)', 'Count': 31609},
    {'Label': 'Natural Gas Distribution', 'Count': 31525},
    {'Label': 'Communications & Networking (NEC)', 'Count': 30862},
    {'Label': 'Apparel & Accessories (NEC)', 'Count': 30682},
    {'Label': 'Personal & Car Loans', 'Count': 30636},
    {'Label': 'Life Insurance', 'Count': 30545}]}}}

Response does not contain DataFrame

#### Search with Navigator option

In [10]:
response = search.Definition(
    view=search.SearchViews.COMMODITY_QUOTES,
    query="cheese",
    navigators="ExchangeName"
).get_data()

response.data.df

,DocumentTitle,BusinessEntity,PI,RIC,PermID
0,"CME Cash Settled Cheese Electronic Commodity Future Continuation 1, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,273610776,CSCc1,21622940491
1,"Cash Settled Cheese Futures Chain Contracts, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,272623267,0#CSC:,21622425217
2,"CME Cash Settled Cheese Electronic Commodity Future Dec 2021, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,406809544,CSCZ1,21727643040
3,"CME Cash Settled Cheese Electronic Commodity Future Nov 2021, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,402256891,CSCX1,21723899060
4,"CME Cash Settled Cheese Electronic Commodity Future Jan 2022, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,413501786,CSCF2,21733097271
5,"CME Cash Settled Cheese Electronic Commodity Future Feb 2022, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,419119906,CSCG2,21737604992
6,"CME Cash Settled Cheese Electronic Commodity Future Mar 2022, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,427664132,CSCH2,21744350317
7,"CME Cash Settled Cheese Electronic Commodity Future Apr 2022, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,432796175,CSCJ2,21748334445
8,"CME Cash Settled Cheese Electronic Commodity Future May 2022, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,439042441,CSCK2,21753182135
9,"CME Cash Settled Cheese Electronic Commodity Future Jun 2022, Commodity Future, Chicago Mercantile Exchange",QUOTExCOMMODITY,444997903,CSCM2,21757842054

In [11]:
response.data.raw["Navigators"]['ExchangeName']

{'Buckets': [{'Label': 'CME:Index and Options Market', 'Count': 15876},
  {'Label': 'Chicago Mercantile Exchange', 'Count': 4283},
  {'Label': 'INTL FCStone Inc', 'Count': 2550},
  {'Label': 'Source is a Refinitiv Contributor', 'Count': 1498},
  {'Label': 'US Department of Agriculture', 'Count': 96},
  {'Label': 'Commodity Futures Trading Commission', 'Count': 66},
  {'Label': 'Complete Intelligence', 'Count': 42},
  {'Label': 'Intercontinental Exchange US', 'Count': 31},
  {'Label': 'US Bureau Of Labor Statistics', 'Count': 10},
  {'Label': 'DCA Markets B.V. - DCA-Markets-PRA Price Reporting Agent',
   'Count': 4},
  {'Label': 'European Energy Exchange', 'Count': 4},
  {'Label': 'European Commission', 'Count': 3},
  {'Label': 'ESALQ', 'Count': 2},
  {'Label': 'CME:International Monetary Market', 'Count': 1}]}

In [12]:
response = search.Definition(
    view=search.SearchViews.GOV_CORP_INSTRUMENTS,
    top=0,
    navigators="Currency(buckets:10,desc:sum_FaceOutstandingUSD,calc:max_CouponRate)"
).get_data()

response.data.raw

{'Total': 8704177,
 'Hits': [],
 'Navigators': {'Currency': {'Buckets': [{'Label': 'USD',
     'Count': 3527350,
     'max_CouponRate': 1800.0,
     'sum_FaceOutstandingUSD': 48824913978323.0},
    {'Label': 'EUR',
     'Count': 1043188,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 23168766121367.0},
    {'Label': 'CNY',
     'Count': 302394,
     'max_CouponRate': 72.0,
     'sum_FaceOutstandingUSD': 19513128264679.0},
    {'Label': 'JPY',
     'Count': 443259,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 12601351396044.018},
    {'Label': 'GBP',
     'Count': 186123,
     'max_CouponRate': 120.0,
     'sum_FaceOutstandingUSD': 4652805308585.0},
    {'Label': 'INR',
     'Count': 106060,
     'max_CouponRate': 42.75,
     'sum_FaceOutstandingUSD': 2638007694215.0},
    {'Label': 'CAD',
     'Count': 301604,
     'max_CouponRate': 100.0,
     'sum_FaceOutstandingUSD': 2580140875790.0},
    {'Label': 'KRW',
     'Count': 383416,
     'max_CouponRate': 46.41,
     'sum_FaceOutstandingUSD': 2289788830774.5947},
    {'Label': 'AUD',
     'Count': 137255,
     'max_CouponRate': 340.0,
     'sum_FaceOutstandingUSD': 1572006407837.4468},
    {'Label': 'BRL',
     'Count': 53918,
     'max_CouponRate': 108.5,
     'sum_FaceOutstandingUSD': 840435512255.241}]}}}

#### Sub-navigator

In [13]:
response = search.Definition(
    view=search.SearchViews.PEOPLE,
    top=0,
    navigators="FirstName(buckets:3,sub:LastName(buckets:2))"
).get_data()

response.data.raw["Navigators"]["FirstName"]["Buckets"]

[{'Label': 'John',
  'Count': 40404,
  'LastName': {'Buckets': [{'Label': 'Murphy', 'Count': 107},
    {'Label': 'Smith', 'Count': 105}]}},
 {'Label': 'David',
  'Count': 39096,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 238},
    {'Label': 'Williams', 'Count': 161}]}},
 {'Label': 'Michael',
  'Count': 37650,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 180},
    {'Label': 'Brown', 'Count': 122}]}}]

#### Search with order_by option

In [14]:
response = search.Definition(
    view=search.SearchViews.PEOPLE,
    query="ceo",
    order_by="YearOfBirth desc,LastName,FirstName",
    select="YearOfBirth,DocumentTitle"
).get_data()

response.data.df

,DocumentTitle,YearOfBirth
0,"Shu Yao - Dongjiang Environmental Co Ltd - Ex-Chief Executive Officer, Executive Director",1996
1,Alberto Rizzoli - V7 Ltd - Chief Executive Officer,1993
2,Christian Besenbruch - Deep Render Ltd - Chief Executive Officer and Co-Founder,1992
3,"Snigdha Mothukuri - Jeevan Scientific Technology Ltd - Chief Executive Officer, Executive Director",1992
4,"Ivan Aleksandrovich Plekhanov - Territorial'naya Generiruyushchaya Kompaniya No2 PAO - Executive Director, Adviser to General Director (CEO)",1992
5,Tess Isabelle Cosad - Stepone Fertility Ltd - Chief Executive Officer and Marketing Strategist,1991
6,"Grigory Sergeevich Sandulov - Omskiy Rechnoy Port AO - General Director (CEO), Director",1991
7,Yehonatan Shachar - Upsellon Brands Holdings Ltd - Chief Executive Officer,1991
8,"Myeong Jin Chae - Arion Technology Inc - Chief Executive Officer, Director",1990
9,"Pedro de Godoy Bueno - Diagnosticos da America SA - Chief Executive Officer, Director",1990

#### Search with group_by option

In [15]:
response = search.Definition(
    view=search.SearchViews.INDICATOR_QUOTES,
    query="rate",
    group_by="CentralBankName",
    group_count=2,
    select="CentralBankName,DocumentTitle,RIC"
).get_data()

response.data.df

,DocumentTitle,RIC,CentralBankName
0,"United States, Policy Rates, Fed Funds Target Rate, Reuters Polls, Daily, The Federal Open Market Committee",USFOMC=ECI,Federal Reserve System
1,"United States, Policy Rates, Fed Overnight Repo, Reuters Polls, Daily, Federal Reserve, United States",USRRP=ECI,Federal Reserve System
2,"Euro Zone, Policy Rates, ECB Main refinancing, Fixed Rate (Announcement Dates), Reuters Polls, Monthly, ECB - European Central Bank",EUECBR=ECI,European Central Bank
3,"Euro Zone, Policy Rates, ECB Deposit Rate, Reuters Polls, Monthly, ECB - European Central Bank",EUECBD=ECI,European Central Bank
4,"Turkey, Policy Rates, Central Bank 1 Week Repo Lending Rate, Reuters Polls, Monthly, Central Bank of the Republic of Turkey",TRINT=ECI,Central Bank of the Republic of Turkey
5,"Turkey, Policy Rates, Overnight Lending Rate, Reuters Polls, Monthly, Central Bank of the Republic of Turkey",TRONR=ECI,Central Bank of the Republic of Turkey
6,"South Africa, Policy Rates, Repo Rate, Reuters Polls, Monthly, South African Reserve Bank",ZAREPO=ECI,South African Reserve Bank
7,"South Africa, Policy Rates, Prime Overdraft Rate, Reuters Polls, Monthly, South African Reserve Bank",ZAPRIM=ECI,South African Reserve Bank
8,"Indonesia, Policy Rates, Deposit Facility Rate, Reuters Polls, Monthly, Bank Indonesia",IDCBID=ECI,Bank Indonesia
9,"Indonesia, Policy Rates, Lending Facility Rate, Reuters Polls, Monthly, Bank Indonesia",IDCBIL=ECI,Bank Indonesia

#### Search For People

In [16]:
response = search.Definition(
    query="cfo",
    view=search.SearchViews.PEOPLE
).get_data()

response.data.df

,PermID,PI,BusinessEntity,DocumentTitle
0,34415553383,34415553383,PERSON,"Amy E. Hood - Microsoft Corp - Chief Financial Officer, Executive Vice President"
1,34414554748,34414554748,PERSON,"Luca Maestri - Apple Inc - Chief Financial Officer, Senior Vice President"
2,34417610894,34417610894,PERSON,"Brian T. Olsavsky - Amazon.com Inc - Chief Financial Officer, Senior Vice President"
3,34413960665,34413960665,PERSON,"Ruth M. Porat - Alphabet Inc - Chief Financial Officer, Senior Vice President"
4,34414804241,34414804241,PERSON,David M. Wehner - Meta Platforms Inc - Chief Financial Officer
5,34413152672,34413152672,PERSON,"Marc D. Hamburg - Berkshire Hathaway Inc - Chief Financial Officer, Senior Vice President"
6,34414966250,34414966250,PERSON,Andrew K. Klatt - Berkshire Hathaway Inc - CFO & COO
7,34414263702,34414263702,PERSON,"Maggie Wu - Alibaba Group Holding Ltd - Chief Financial Officer, Director"
8,34414907131,34414907131,PERSON,"John Lo - Tencent Holdings Ltd - Chief Financial Officer, Senior Vice President"
9,34413340523,34413340523,PERSON,"Vasant M. Prabhu - Visa Inc - Vice Chairman of the Board, Chief Financial Officer"

### Lookup

In [17]:
response = search.lookup.Definition(
    view=search.SearchViews.INSTRUMENTS,                               # Required parameter
    scope="RIC",                                                       # Required parameter
    terms="MSFT.O,AAPL.O,GOOG.O,IBM.N,KBANK.BK,SCC.BK",                # Required parameter
    select="BusinessEntity,DocumentTitle,CUSIP,SEDOL",                 # Required parameter
).get_data()

response.data.df

,CUSIP,SEDOL,BusinessEntity,DocumentTitle
MSFT.O,594918104,<NA>,INSTRUMENTxEQUITY,"Microsoft Corp, Ordinary Share"
AAPL.O,037833100,<NA>,INSTRUMENTxEQUITY,"Apple Inc, Ordinary Share"
GOOG.O,02079K107,<NA>,INSTRUMENTxEQUITY,"Alphabet Inc, Ordinary Share"
KBANK.BK,<NA>,6888783,INSTRUMENTxEQUITY,"Kasikornbank PCL, Ordinary Share"
SCC.BK,<NA>,6609917,INSTRUMENTxEQUITY,"Siam Cement PCL, Ordinary Share"

In [18]:
response = search.lookup.Definition(
    view=search.SearchViews.SEARCH_ALL,                              # Required parameter
    scope="RIC",                                                     # Required parameter
    terms="A,B,NOSUCHRIC,C,D",                                       # Required parameter
    select="BusinessEntity,DocumentTitle",                           # Required parameter
).get_data()

response.data.df

  BusinessEntity                                                DocumentTitle
A  QUOTExEQUITY   Agilent Technologies Inc, Ordinary Share, NYSE Consolidated
B  QUOTExEQUITY   Barnes Group Inc, Ordinary Share, NYSE Consolidated
C  QUOTExEQUITY   Citigroup Inc, Ordinary Share, NYSE Consolidated
D  QUOTExEQUITY   Dominion Energy Inc, Ordinary Share, NYSE Consolidated

## Close the session

In [20]:
rd.close_session()