# Refinitiv Data Library for Python
## Content - Search, Lookup and View Metadata
This notebook demonstrates how to utilise the Search API using the Refinitiv Data Platform OR via Refinitiv Eikon/Workspace.

For more details on the Search API refer to the following:

* The article, [Building Search into your Application Workflow](https://developers.refinitiv.com/en/article-catalog/article/building-search-into-your-application-workflow), provides an overview of the capabilities of the Search service including tips and tricks and many useful techniques.

* Search API documentation: [Search Reference Guide](https://apidocs.refinitiv.com/Apps/ApiDocs#/details/L2Rpc2NvdmVyeS9zZWFyY2gvdjE=/Lw==/POST/README)

## Import the library and load credentials

Credentials used by this and the other tutorials notebooks are stored in the **Configuration/credentials.ipynb** file.     

You should have edited the **Configuration/credentials.ipynb** to set your credentials as part of the **Quick Start** step.

In [1]:
from refinitiv.data.content import search
import pandas as pd
import json

%run ../../Configuration/credentials.ipynb

## Open the session of your choice

Use our helper function in the Credentials notebook, **open_session(session_type)**, to create and open a session to connect to the 
- Refinitiv Data Platform directly (session_type="rdp") or via 
- Eikon 4 or Refinitiv Workspace (session_type="desktop")   

You can also set a default in the **credentials** notebook

**Note**: You cannot currently use the Search API via a Deployed session

In [2]:
open_session()

#### General Search

In [3]:
response = search.Definition("IBM Bonds").get_data()
response.data.df

,DocumentTitle,PermID,PI,BusinessEntity,RIC
0,"International Business Machines Corp, Fixed Ma...",44657599150,0x0004051b94d20854,INSTRUMENTxFIXEDINCOMExGOVCORP,459200HX2=
1,"International Business Machines Corp, Plain Va...",46642939296,0x00102c28b5f20b58,INSTRUMENTxFIXEDINCOMExGOVCORP,459200JQ5=
2,"International Business Machines Corp, Plain Va...",192841929423,0x00102c2452251a75,INSTRUMENTxFIXEDINCOMExGOVCORP,459200JX0=
3,"International Business Machines Corp, Plain Va...",44640212240,0x0004050e34388b88,INSTRUMENTxFIXEDINCOMExGOVCORP,459200HG9=
4,"International Business Machines Corp, Plain Va...",46635711098,0x00102c05c4dd0222,INSTRUMENTxFIXEDINCOMExGOVCORP,US127166528=
5,"International Business Machines Corp, Plain Va...",46637038358,0x00102c80bf6b046c,INSTRUMENTxFIXEDINCOMExGOVCORP,459200JC6=
6,"International Business Machines Corp, Plain Va...",192826899363,0x00102c53ff1f1897,INSTRUMENTxFIXEDINCOMExGOVCORP,US194445601=
7,"International Business Machines Corp, Plain Va...",44657843041,0x0004051bd47954e3,INSTRUMENTxFIXEDINCOMExGOVCORP,US114316318=
8,"International Business Machines Corp, Plain Va...",44649129642,0x00040513a4865c6c,INSTRUMENTxFIXEDINCOMExGOVCORP,459200HP9=
9,"International Business Machines Corp, Plain Va...",44653695161,0x00040517bba31719,INSTRUMENTxFIXEDINCOMExGOVCORP,459200HU8=

#### Specify number of rows to fetch

In [4]:
response = search.Definition("IBM Bonds", top=100).get_data()
response.data.df

,DocumentTitle,PermID,PI,BusinessEntity,RIC
0,"International Business Machines Corp, Fixed Ma...",44657599150,0x0004051b94d20854,INSTRUMENTxFIXEDINCOMExGOVCORP,459200HX2=
1,"International Business Machines Corp, Plain Va...",46642939296,0x00102c28b5f20b58,INSTRUMENTxFIXEDINCOMExGOVCORP,459200JQ5=
2,"International Business Machines Corp, Plain Va...",192841929423,0x00102c2452251a75,INSTRUMENTxFIXEDINCOMExGOVCORP,459200JX0=
3,"International Business Machines Corp, Plain Va...",44640212240,0x0004050e34388b88,INSTRUMENTxFIXEDINCOMExGOVCORP,459200HG9=
4,"International Business Machines Corp, Plain Va...",46635711098,0x00102c05c4dd0222,INSTRUMENTxFIXEDINCOMExGOVCORP,US127166528=
...,...,...,...,...,...
95,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037edee,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
96,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037eeed,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
97,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037efec,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
98,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037f0f3,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>
99,"IBM Credit LLC, Plain Vanilla Fixed Coupon Bon...",<NA>,0x000034000037f1f2,INSTRUMENTxFIXEDINCOMExGOVCORP,<NA>

#### Filter Expressions

In [5]:
response = search.Definition(
    view=search.SearchViews.GOV_CORP_INSTRUMENTS,
    select="ISIN,RIC,IssueDate,Currency,FaceIssuedTotal,CouponRate,MaturityDate", 
    filter="IssuerTicker eq 'IBM' and IsActive eq true and AssetStatus ne 'MAT'"
).get_data()
response.data.df

,CouponRate,MaturityDate,FaceIssuedTotal,ISIN,Currency,IssueDate,RIC
0,0.0,2021-09-27T00:00:00.000Z,<NA>,US45920FWT10,USD,2021-08-25T00:00:00.000Z,45920FWT1=
1,0.0,2021-09-28T00:00:00.000Z,<NA>,US45920FWU82,USD,2021-08-25T00:00:00.000Z,45920FWU8=
2,0.0,2021-09-29T00:00:00.000Z,<NA>,US45920FWV65,USD,2021-08-25T00:00:00.000Z,45920FWV6=
3,0.0,2021-09-30T00:00:00.000Z,<NA>,US45920FWW49,USD,2021-08-25T00:00:00.000Z,45920FWW4=
4,0.70175,2021-11-06T00:00:00.000Z,1100000000.0,US459200HX26,USD,2014-11-06T00:00:00.000Z,459200HX2=
5,2.5,2022-01-27T00:00:00.000Z,1000000000.0,US459200JQ56,USD,2017-01-27T00:00:00.000Z,459200JQ5=
6,2.85,2022-05-13T00:00:00.000Z,2750000000.0,US459200JX08,USD,2019-05-15T00:00:00.000Z,459200JX0=
7,1.875,2022-08-01T00:00:00.000Z,1000000000.0,US459200HG92,USD,2012-07-30T00:00:00.000Z,459200HG9=
8,2.625,2022-08-05T00:00:00.000Z,300000000.0,XS1271665280,GBP,2015-08-05T00:00:00.000Z,US127166528=
9,2.875,2022-11-09T00:00:00.000Z,900000000.0,US459200JC60,USD,2015-11-09T00:00:00.000Z,459200JC6=

#### Properties - Metadata

In [6]:
response = search.metadata.Definition(
    view = search.SearchViews.GOV_CORP_INSTRUMENTS  # Required parameterc
).get_data()

# for Pandas Display purpose only
pd.set_option("display.max_columns", None) 
pd.set_option("display.max_rows", 10)  # Just show 10 rows
pd.set_option("display.max_colwidth", 1)  

response.data.df

,,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AccrualDate,AccrualDate,Date,True,True,True,False,False,False
AccruedInterest,AccruedInterest,Double,True,True,True,False,False,False
ActiveEstimatesExist,ActiveEstimatesExist,Boolean,True,False,False,False,False,False
AdtLocalCurrencyValue,AdtLocalCurrencyValue,String,True,False,False,False,False,False
AdtLocalCurrencyValueName,AdtLocalCurrencyValueName,String,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...
WorstStandardYield,WorstStandardYield,Double,True,True,True,False,False,False
WorstYearsToRedem,WorstYearsToRedem,Double,True,True,True,False,False,False
YieldCurveBenchmarkRIC,YieldCurveBenchmarkRIC,String,False,False,False,False,False,False
YieldTypeDescription,YieldTypeDescription,String,True,False,False,False,False,False
ZCodeValue,ZCodeValue,String,True,True,False,False,False,True

#### Navigators

In [7]:
response = search.Definition(
    top=0,
    navigators="RCSTRBC2012Leaf"
).get_data()

#### Response Data Structure

In [9]:
# Check if request was successful
if (response.is_success):
    # Should have raw data when is_success==true
    if response.data.raw:
        display(response.data.raw)
    else:
        print("Response does not contain raw data")    
    # Check if the response contains a Dataframe too?
    if (not response.data.df.empty):
        display(response.data.df)
    else:
        print("\nResponse does not contain DataFrame")
else: 
    # Something went wrong
    print(f"Not Successful : {response.http_status}")

{'Total': 154531502,
 'Hits': [],
 'Navigators': {'RCSTRBC2012Leaf': {'Buckets': [{'Label': 'Banks (NEC)',
     'Count': 3971507},
    {'Label': 'Corporate Financial Services (NEC)', 'Count': 2936831},
    {'Label': 'Corporate Banks', 'Count': 1485293},
    {'Label': 'Retail & Mortgage Banks', 'Count': 1274626},
    {'Label': 'Investment Banking & Brokerage Services (NEC)',
     'Count': 707824},
    {'Label': 'Public Finance Activities', 'Count': 664587},
    {'Label': 'Consumer Lending (NEC)', 'Count': 369674},
    {'Label': 'Government & Government Finance (NEC)', 'Count': 331147},
    {'Label': 'Electric Utilities (NEC)', 'Count': 318419},
    {'Label': 'Investment Management & Fund Operators (NEC)', 'Count': 310528},
    {'Label': 'Diversified Investment Services', 'Count': 291765},
    {'Label': 'Wealth Management', 'Count': 286376},
    {'Label': 'Investment Holding Companies (NEC)', 'Count': 282983},
    {'Label': 'Professional Information Services (NEC)', 'Count': 278056},
    {'Label': 'Construction & Engineering (NEC)', 'Count': 267914},
    {'Label': 'Real Estate Rental, Development & Operations (NEC)',
     'Count': 258742},
    {'Label': 'Business Support Services (NEC)', 'Count': 236129},
    {'Label': 'Building Contractors', 'Count': 204577},
    {'Label': 'Financial & Commodity Market Operators & Service Providers (NEC)',
     'Count': 183756},
    {'Label': 'Management Consulting Services', 'Count': 165299},
    {'Label': 'Investment Banking', 'Count': 150236},
    {'Label': 'Software (NEC)', 'Count': 136303},
    {'Label': 'IT Services & Consulting (NEC)', 'Count': 133820},
    {'Label': 'UK Investment Trusts', 'Count': 120515},
    {'Label': 'Investment Management', 'Count': 111566},
    {'Label': 'Real Estate Services (NEC)', 'Count': 109984},
    {'Label': 'Consumer Leasing', 'Count': 104319},
    {'Label': 'Hedge Funds', 'Count': 103381},
    {'Label': 'Pharmaceuticals (NEC)', 'Count': 99309},
    {'Label': 'Supermarkets & Convenience Stores', 'Count': 97400},
    {'Label': 'Government Administration Activities', 'Count': 95333},
    {'Label': 'Integrated Telecommunications Services (NEC)', 'Count': 95282},
    {'Label': 'Oil & Gas Exploration and Production (NEC)', 'Count': 87873},
    {'Label': 'Brokerage Services', 'Count': 83382},
    {'Label': 'Industrial Machinery & Equipment (NEC)', 'Count': 82994},
    {'Label': 'Commodity Chemicals (NEC)', 'Count': 80996},
    {'Label': 'Hospitals, Clinics & Primary Care Services', 'Count': 80768},
    {'Label': 'Food Processing (NEC)', 'Count': 75061},
    {'Label': 'Insurance Brokers', 'Count': 74906},
    {'Label': 'Auto Vehicles, Parts & Service Retailers (NEC)',
     'Count': 72926},
    {'Label': 'Restaurants & Bars (NEC)', 'Count': 68945},
    {'Label': 'Industrial Machinery', 'Count': 64337},
    {'Label': 'Residential Builders - Single Homes', 'Count': 61838},
    {'Label': 'Multiline Utilities', 'Count': 60674},
    {'Label': 'Construction Materials (NEC)', 'Count': 59999},
    {'Label': 'Electrical Components & Equipment (NEC)', 'Count': 58514},
    {'Label': 'Auto, Truck & Motorcycle Parts (NEC)', 'Count': 56496},
    {'Label': 'Land Division & Subdivision', 'Count': 55055},
    {'Label': 'Hotels & Motels', 'Count': 54419},
    {'Label': 'Shell Companies', 'Count': 53867},
    {'Label': 'Closed End Funds', 'Count': 53607},
    {'Label': 'Miscellaneous Educational Service Providers', 'Count': 53531},
    {'Label': 'Biotechnology & Medical Research (NEC)', 'Count': 52444},
    {'Label': 'Freight Trucking', 'Count': 52134},
    {'Label': 'Auto & Truck Manufacturers (NEC)', 'Count': 51756},
    {'Label': 'Consumer Goods Conglomerates', 'Count': 51532},
    {'Label': 'Office Real Estate Rental & Development', 'Count': 50333},
    {'Label': 'Commercial Loans', 'Count': 49802},
    {'Label': 'Civil Engineers & Architects', 'Count': 49248},
    {'Label': 'Oil & Gas Refining and Marketing (NEC)', 'Count': 48810},
    {'Label': 'Highway & Bridge Construction', 'Count': 48522},
    {'Label': 'Life & Health Insurance (NEC)', 'Count': 48158},
    {'Label': 'Plastics', 'Count': 46704},
    {'Label': 'Iron & Steel (NEC)', 'Count': 46644},
    {'Label': 'Metallic Rolling & Drawing Products', 'Count': 46519},
    {'Label': 'Personal Services (NEC)', 'Count': 45480},
    {'Label': 'Healthcare Facilities & Services (NEC)', 'Count': 44207},
    {'Label': 'Plumbing Fixtures & Fittings', 'Count': 43200},
    {'Label': 'Drug Retailers (NEC)', 'Count': 42839},
    {'Label': 'Oil & Gas Transportation Services (NEC)', 'Count': 41004},
    {'Label': 'Diversified Mining', 'Count': 40802},
    {'Label': 'Wireless Telecommunications Services (NEC)', 'Count': 39945},
    {'Label': 'Passenger Transportation, Ground & Sea (NEC)', 'Count': 39088},
    {'Label': 'Homebuilding (NEC)', 'Count': 39051},
    {'Label': 'Semiconductors (NEC)', 'Count': 38562},
    {'Label': 'Commercial Leasing', 'Count': 37742},
    {'Label': 'Maintenance & Repair Services', 'Count': 37601},
    {'Label': 'Residential Real Estate Rental & Development', 'Count': 37244},
    {'Label': 'Gasoline Stations', 'Count': 37194},
    {'Label': 'Waste Management, Disposal & Recycling Services',
     'Count': 36453},
    {'Label': 'Medical Equipment, Supplies & Distribution (NEC)',
     'Count': 35997},
    {'Label': 'Legal Services', 'Count': 35570},
    {'Label': 'Property & Casualty Insurance (NEC)', 'Count': 34678},
    {'Label': 'Petroleum Refining', 'Count': 34011},
    {'Label': 'Ground Freight & Logistics (NEC)', 'Count': 33746},
    {'Label': 'Commercial Buildings', 'Count': 33684},
    {'Label': 'Broadcasting (NEC)', 'Count': 33589},
    {'Label': 'Commercial REITs (NEC)', 'Count': 33316},
    {'Label': 'Coal (NEC)', 'Count': 33267},
    {'Label': 'Natural Gas Utilities (NEC)', 'Count': 32935},
    {'Label': 'Cement & Concrete Manufacturing', 'Count': 32337},
    {'Label': 'Freight Logistics', 'Count': 31971},
    {'Label': 'Private Banks', 'Count': 31894},
    {'Label': 'Bio Therapeutic Drugs', 'Count': 31716},
    {'Label': 'Food Retail & Distribution (NEC)', 'Count': 31498},
    {'Label': 'Personal Products (NEC)', 'Count': 31450},
    {'Label': 'Gold Mining', 'Count': 31189},
    {'Label': 'Personal & Car Loans', 'Count': 31108},
    {'Label': 'Advertising Agency', 'Count': 30980},
    {'Label': 'Communications & Networking (NEC)', 'Count': 30723}]}}}

Response does not contain DataFrame

#### Search with Navigator option

In [10]:
response = search.Definition(
    view=search.SearchViews.COMMODITY_QUOTES,
    query="cheese",
    navigators="ExchangeName"
).get_data()

response.data.df

,DocumentTitle,PermID,PI,BusinessEntity,RIC
0,"CME Cash Settled Cheese Electronic Commodity Future Continuation 1, Commodity Future, Chicago Mercantile Exchange",21622940491,273610776,QUOTExCOMMODITY,CSCc1
1,"Cash Settled Cheese Futures Chain Contracts, Commodity Future, Chicago Mercantile Exchange",21622425217,272623267,QUOTExCOMMODITY,0#CSC:
2,"CME Cash Settled Cheese Electronic Commodity Future Sep 2021, Commodity Future, Chicago Mercantile Exchange",21714572907,390497653,QUOTExCOMMODITY,CSCU1
3,"CME Cash Settled Cheese Electronic Commodity Future Oct 2021, Commodity Future, Chicago Mercantile Exchange",21718846354,396055563,QUOTExCOMMODITY,CSCV1
4,"CME Cash Settled Cheese Electronic Commodity Future Nov 2021, Commodity Future, Chicago Mercantile Exchange",21723899060,402256891,QUOTExCOMMODITY,CSCX1
5,"CME Cash Settled Cheese Electronic Commodity Future Dec 2021, Commodity Future, Chicago Mercantile Exchange",21727643040,406809544,QUOTExCOMMODITY,CSCZ1
6,"CME Cash Settled Cheese Electronic Commodity Future Jan 2022, Commodity Future, Chicago Mercantile Exchange",21733097271,413501786,QUOTExCOMMODITY,CSCF2
7,"CME Cash Settled Cheese Electronic Commodity Future Feb 2022, Commodity Future, Chicago Mercantile Exchange",21737604992,419119906,QUOTExCOMMODITY,CSCG2
8,"CME Cash Settled Cheese Electronic Commodity Future Mar 2022, Commodity Future, Chicago Mercantile Exchange",21744350317,427664132,QUOTExCOMMODITY,CSCH2
9,"CME Cash Settled Cheese Electronic Commodity Future Apr 2022, Commodity Future, Chicago Mercantile Exchange",21748334445,432796175,QUOTExCOMMODITY,CSCJ2

In [10]:
response.data.raw["Navigators"]['ExchangeName']

{'Buckets': [{'Label': 'CME:Index and Options Market', 'Count': 18183},
  {'Label': 'Chicago Mercantile Exchange', 'Count': 4742},
  {'Label': 'INTL FCStone Inc', 'Count': 2550},
  {'Label': 'Source is a Refinitiv Contributor', 'Count': 1498},
  {'Label': 'US Department of Agriculture', 'Count': 96},
  {'Label': 'Commodity Futures Trading Commission', 'Count': 66},
  {'Label': 'Complete Intelligence', 'Count': 40},
  {'Label': 'Intercontinental Exchange US', 'Count': 31},
  {'Label': 'US Bureau Of Labor Statistics', 'Count': 10},
  {'Label': 'DCA Markets B.V. - DCA-Markets-PRA Price Reporting Agent',
   'Count': 4},
  {'Label': 'European Energy Exchange', 'Count': 4},
  {'Label': 'European Commission', 'Count': 3},
  {'Label': 'ESALQ', 'Count': 2},
  {'Label': 'CME:International Monetary Market', 'Count': 1}]}

In [11]:
response = search.Definition(
    view=search.SearchViews.GOV_CORP_INSTRUMENTS,
    top=0,
    navigators="Currency(buckets:10,desc:sum_FaceOutstandingUSD,calc:max_CouponRate)"
).get_data()

response.data.raw

{'Total': 8461279,
 'Hits': [],
 'Navigators': {'Currency': {'Buckets': [{'Label': 'USD',
     'Count': 3458237,
     'max_CouponRate': 1800.0,
     'sum_FaceOutstandingUSD': 47851435896682.0},
    {'Label': 'EUR',
     'Count': 1029441,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 24161890795970.0},
    {'Label': 'CNY',
     'Count': 290936,
     'max_CouponRate': 72.0,
     'sum_FaceOutstandingUSD': 18677327853604.0},
    {'Label': 'JPY',
     'Count': 432490,
     'max_CouponRate': 500.0,
     'sum_FaceOutstandingUSD': 13268695799530.018},
    {'Label': 'GBP',
     'Count': 182311,
     'max_CouponRate': 120.0,
     'sum_FaceOutstandingUSD': 4745332891596.0},
    {'Label': 'INR',
     'Count': 103924,
     'max_CouponRate': 42.75,
     'sum_FaceOutstandingUSD': 2633922635388.0},
    {'Label': 'CAD',
     'Count': 297198,
     'max_CouponRate': 100.0,
     'sum_FaceOutstandingUSD': 2529255947739.0},
    {'Label': 'KRW',
     'Count': 378242,
     'max_CouponRate': 46.41,
     'sum_FaceOutstandingUSD': 2296633221729.6816},
    {'Label': 'AUD',
     'Count': 133351,
     'max_CouponRate': 120.96,
     'sum_FaceOutstandingUSD': 1584533003949.7375},
    {'Label': 'BRL',
     'Count': 41789,
     'max_CouponRate': 108.5,
     'sum_FaceOutstandingUSD': 908062740846.5195}]}}}

#### Sub-navigator

In [12]:
response = search.Definition(
    view=search.SearchViews.PEOPLE,
    top=0,
    navigators="FirstName(buckets:3,sub:LastName(buckets:2))"
).get_data()

response.data.raw["Navigators"]["FirstName"]["Buckets"]

[{'Label': 'John',
  'Count': 39840,
  'LastName': {'Buckets': [{'Label': 'Murphy', 'Count': 105},
    {'Label': 'Lee', 'Count': 104}]}},
 {'Label': 'David',
  'Count': 38486,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 231},
    {'Label': 'Williams', 'Count': 158}]}},
 {'Label': 'Michael',
  'Count': 37062,
  'LastName': {'Buckets': [{'Label': 'Smith', 'Count': 179},
    {'Label': 'Brown', 'Count': 119}]}}]

#### Search with order_by option

In [13]:
response = search.Definition(
    view=search.SearchViews.PEOPLE,
    query="ceo",
    order_by="YearOfBirth desc,LastName,FirstName",
    select="YearOfBirth,DocumentTitle"
).get_data()

response.data.df

,YearOfBirth,DocumentTitle
0,1996,"Shu Yao - Dongjiang Environmental Co Ltd - Ex-Chief Executive Officer, Executive Director"
1,1993,Alberto Rizzoli - V7 Ltd - Chief Executive Officer
2,1992,Christian Besenbruch - Deep Render Ltd - Chief Executive Officer and Co-Founder
3,1992,"Ivan Aleksandrovich Plekhanov - Territorial'naya Generiruyushchaya Kompaniya No2 PAO - Executive Director, Adviser to General Director (CEO)"
4,1991,Tess Isabelle Cosad - Stepone Fertility Ltd - Chief Executive Officer and Marketing Strategist
5,1991,"Grigory Sergeevich Sandulov - Omskiy Rechnoy Port AO - General Director (CEO), Director"
6,1991,Yehonatan Shachar - Upsellon Brands Holdings Ltd - Chief Executive Officer
7,1990,"Myeong Jin Chae - Arion Technology Inc - Chief Executive Officer, Director"
8,1990,"Pedro de Godoy Bueno - Diagnosticos da America SA - Chief Executive Officer, Director"
9,1990,"Hikaru Ohno - Cyber Security Cloud Inc - President, Chief Executive Officer, Representative Director"

#### Search with group_by option

In [14]:
response = search.Definition(
    view=search.SearchViews.INDICATOR_QUOTES,
    query="rate",
    group_by="CentralBankName",
    group_count=2,
    select="CentralBankName,DocumentTitle,RIC"
).get_data()

response.data.df

,DocumentTitle,RIC,CentralBankName
0,"United States, Policy Rates, Fed Funds Target Rate, Reuters Polls, Daily, The Federal Open Market Committee",USFOMC=ECI,Federal Reserve System
1,"United States, Policy Rates, Fed Overnight Repo, Reuters Polls, Daily, Federal Reserve, United States",USRRP=ECI,Federal Reserve System
2,"Euro Zone, Policy Rates, ECB Main refinancing, Fixed Rate (Announcement Dates), Reuters Polls, Monthly, ECB - European Central Bank",EUECBR=ECI,European Central Bank
3,"Euro Zone, Policy Rates, ECB Deposit Rate, Reuters Polls, Monthly, ECB - European Central Bank",EUECBD=ECI,European Central Bank
4,"Australia, Policy Rates, Cash Target Rate, Reuters Polls, Monthly, Reserve Bank of Australia",AUCBIR=ECI,Reserve Bank Of Australia
5,"Australia, RBA Cash Rate-Median, Reuters Polls, Monthly, Reuters",pAUCBIR=M,Reserve Bank Of Australia
6,"Chile, Policy Rates, Monetary Policy Interest Rate, Reuters Polls, Monthly, Central Bank of Chile",CLINTR=ECI,The Central Bank of Chile
7,"Chile, Interest Rate-Median, Reuters Polls, Monthly, Reuters",pCLINTR=M,The Central Bank of Chile
8,"Colombia, Policy Rates, Intervention Rate, Reuters Polls, Monthly, Banco de la Republica, Colombia",COCBIR=ECI,Central Bank of Colombia
9,"Colombia, Intervention Rate - THE ROYAL BANK OF SCOTLAND PUBLIC LIMITED COMPANY, Reuters Polls, Monthly, Reuters",pCOCBIR=4296555135,Central Bank of Colombia

#### Search For People

In [15]:
response = search.Definition(
    query="cfo",
    view=search.SearchViews.PEOPLE
).get_data()

response.data.df

,PermID,PI,BusinessEntity,DocumentTitle
0,34415553383,34415553383,PERSON,"Amy E. Hood - Microsoft Corp - Chief Financial Officer, Executive Vice President"
1,34414554748,34414554748,PERSON,"Luca Maestri - Apple Inc - Chief Financial Officer, Senior Vice President"
2,34417610894,34417610894,PERSON,"Brian T. Olsavsky - Amazon.com Inc - Chief Financial Officer, Senior Vice President"
3,34413960665,34413960665,PERSON,"Ruth M. Porat - Alphabet Inc - Chief Financial Officer, Senior Vice President"
4,34414804241,34414804241,PERSON,David M. Wehner - Facebook Inc - Chief Financial Officer
5,34413152672,34413152672,PERSON,"Marc D. Hamburg - Berkshire Hathaway Inc - Chief Financial Officer, Senior Vice President"
6,34414966250,34414966250,PERSON,Andrew K. Klatt - Berkshire Hathaway Inc - CFO & COO
7,34414263702,34414263702,PERSON,"Maggie Wu - Alibaba Group Holding Ltd - Chief Financial Officer, Director"
8,34414907131,34414907131,PERSON,"John Lo - Tencent Holdings Ltd - Chief Financial Officer, Senior Vice President"
9,34413340523,34413340523,PERSON,"Vasant M. Prabhu - Visa Inc - Vice Chairman of the Board, Chief Financial Officer"

### Lookup

In [16]:
response = search.lookup.Definition(
    view=search.SearchViews.INSTRUMENTS,                               # Required parameter
    scope="RIC",                                                       # Required parameter
    terms="MSFT.O,AAPL.O,GOOG.O,IBM.N,KBANK.BK,SCC.BK",                # Required parameter
    select="BusinessEntity,DocumentTitle,CUSIP,SEDOL",                 # Required parameter
).get_data()

response.data.df

,CUSIP,BusinessEntity,SEDOL,DocumentTitle
MSFT.O,594918104,INSTRUMENTxEQUITY,<NA>,"Microsoft Corp, Ordinary Share"
AAPL.O,037833100,INSTRUMENTxEQUITY,<NA>,"Apple Inc, Ordinary Share"
GOOG.O,02079K107,INSTRUMENTxEQUITY,<NA>,"Alphabet Inc, Ordinary Share"
KBANK.BK,<NA>,INSTRUMENTxEQUITY,6888783,"Kasikornbank PCL, Ordinary Share"
SCC.BK,<NA>,INSTRUMENTxEQUITY,6609917,"Siam Cement PCL, Ordinary Share"

In [17]:
response = search.lookup.Definition(
    view=search.SearchViews.SEARCH_ALL,                              # Required parameter
    scope="RIC",                                                     # Required parameter
    terms="A,B,NOSUCHRIC,C,D",                                       # Required parameter
    select="BusinessEntity,DocumentTitle",                           # Required parameter
).get_data()

response.data.df

  BusinessEntity                                                DocumentTitle
A  QUOTExEQUITY   Agilent Technologies Inc, Ordinary Share, NYSE Consolidated
B  QUOTExEQUITY   Barnes Group Inc, Ordinary Share, NYSE Consolidated
C  QUOTExEQUITY   Citigroup Inc, Ordinary Share, NYSE Consolidated
D  QUOTExEQUITY   Dominion Energy Inc, Ordinary Share, NYSE Consolidated

## Close the session

In [18]:
close_session()